/* ------------------------------------
COPYRIGHT (C) 2010-2015 LINKAGE SOFTWARE 
 ALL RIGHTS RESERVED.
<AUTHOR>JIANGBB</AUTHOR>
<CREATEDATE>2015-03-23</CREATEDATE>
<DESCRIPTION>休闲年卡开通校验</DESCRIPTION>
------------------------------------ */
CREATE OR REPLACE PROCEDURE SP_RELAX_OPENCHECK
(
	P_RETCODE        	OUT CHAR, 		--RETURN CODE
	P_RETMSG         	OUT VARCHAR2,   --RETURN MESSAGE
	P_CARDSTATUS		OUT CHAR,		--卡片状态 02：已开通,03:卡号不存在或卡状态异常
    P_CARDNO            CHAR,
    P_REMARK   			CHAR
)
AS
    V_TODAY         DATE := SYSDATE;
	V_LEVELFLAG		CHAR(1);		--休闲黑名单等级
	V_ENDDATE		CHAR(8);		--休闲结束日期
	V_CARDTIMES		INT;			--开卡次数
	V_SPARETIMES	INT;			--当年剩余可用次数
BEGIN
	
	--检查卡有效性
	BEGIN
	SP_ACCCHECK(
				P_CARDNO		=>	P_CARDNO		,
				P_CURROPER		=>	''				,
				P_CURRDEPT		=>	''				,
				P_RETCODE		=>	P_RETCODE		,
				P_RETMSG		=>	P_RETMSG
				);
	IF	(P_RETCODE !='0000000000') THEN
		P_CARDSTATUS := '03';
		RETURN;
	END IF;
	END;
	
	--检查是否在休闲卡黑名单信息表中
	BEGIN
		SELECT LEVELFLAG INTO V_LEVELFLAG FROM  TF_F_BLACKACC_XXPARK WHERE CARDNO = P_CARDNO;
		EXCEPTION 
		WHEN NO_DATA_FOUND THEN NULL;
	END;
	
	IF V_LEVELFLAG != NULL THEN
		P_RETCODE 		:= 'I094780001';
		P_RETMSG  		:= '当前卡片已经存在于休闲黑名单中';
		P_CARDSTATUS	:= '03';
		RETURN;
	END IF;
	
	--检查休闲年卡是否已经开卡
	BEGIN
		SELECT ENDDATE,CARDTIMES,SPARETIMES INTO V_ENDDATE,V_CARDTIMES,V_SPARETIMES 
		FROM TF_F_CARDXXPARKACC_SZ WHERE CARDNO = P_CARDNO AND USETAG = '1';
		EXCEPTION 
		WHEN NO_DATA_FOUND THEN NULL;
	END;
	
	IF V_ENDDATE > TO_CHAR(SYSDATE,'YYYYMMDD') THEN
		P_RETCODE 		:= 'I094780002';
		P_RETMSG  		:= '当前卡片已开通休闲年卡功能,到期日为：'||V_ENDDATE;
		P_CARDSTATUS	:= '02';
		RETURN;
	END IF;
	
	IF P_RETCODE = '0000000000' THEN
	P_RETMSG := '';
	RETURN;
	END IF;
END;

/
SHOW ERRORS
