CREATE OR REPLACE PROCEDURE SP_GC_RelaxUpdateDistrabution
(
		P_SESSIONID			CHAR,			--SESSIONID
		P_DISTRABUTIONTYPE	CHAR,			--配送状态
		P_DISTRABUTIONMSG	VARCHAR2,		--配送消息
		
		P_CURROPER			CHAR,
		P_CURRDEPT			CHAR,
		P_RETCODE	        OUT CHAR, 		-- RETURN CODE
		P_RETMSG     	    OUT VARCHAR2	-- RETURN MESSAGE
)
AS
    V_EX          		EXCEPTION;
	V_ORDERCOUNT		INT;
	V_TODAY				DATE := SYSDATE;
    V_SEQNO				CHAR(16);			--流水号
BEGIN
	FOR V_CUR IN (SELECT F0,F1,F2,F3 FROM TMP_ORDER WHERE F0 = P_SESSIONID)
	LOOP
		
		--更新联机休闲年卡订单表
		BEGIN
			UPDATE TF_F_XXOL_ORDER 
				SET ISDISTRABUTION	= P_DISTRABUTIONTYPE,
					DISTRABUTIONMSG = P_DISTRABUTIONMSG
			WHERE	ORDERNO 		= V_CUR.F1;
		   EXCEPTION
			  WHEN OTHERS THEN
				P_RETCODE := 'S094780091';
				P_RETMSG := '更新订单表失败' || SQLERRM;
			  ROLLBACK;RETURN;
		END;
	END LOOP;
   
	P_RETCODE := '0000000000';
	P_RETMSG  := '';
	COMMIT; RETURN;
END;

/

SHOW ERRORS

 