CREATE OR REPLACE PROCEDURE SP_GC_ZZSALECARD
(
    P_ORDERDETAILID    CHAR,      --子订单号
    P_ID        CHAR,
    P_CARDNO          CHAR,
    P_DEPOSIT          INT,
    P_CARDCOST          INT,
    P_OTHERFEE      INT,
    P_CARDTRADENO      CHAR,
    P_CARDTYPECODE    CHAR,
    P_CARDMONEY      INT,
    P_SELLCHANNELCODE  CHAR,
    P_SERSTAKETAG      CHAR,
    P_TRADETYPECODE    CHAR,
    P_CUSTNAME      VARCHAR2,
    P_CUSTSEX          VARCHAR2,
    P_CUSTBIRTH      VARCHAR2,
    P_PAPERTYPECODE    VARCHAR2,
    P_PAPERNO          VARCHAR2,
    P_CUSTADDR      VARCHAR2,
    P_CUSTPOST      VARCHAR2,
    P_CUSTPHONE      VARCHAR2,
    P_CUSTEMAIL      VARCHAR2,
    P_REMARK          VARCHAR2,
    P_CUSTRECTYPECODE  CHAR,
    P_TERMNO      CHAR,
    P_OPERCARDNO    CHAR,

    P_CURRENTTIME      OUT DATE,     -- RETURN OPERATE TIME
    P_SALECARDTRADEID  OUT CHAR,     -- RETURN TRADE ID
    P_RELAXTRADEID    OUT CHAR,     -- RETURN RELAXTRADE ID
    P_CURROPER      CHAR,
    P_CURRDEPT      CHAR,
    P_RETCODE          OUT CHAR,     -- RETURN CODE
    P_RETMSG           OUT VARCHAR2  -- RETURN MESSAGE

)
AS
    V_EX              EXCEPTION;
  V_TODAY        DATE := SYSDATE;
    V_SEQNO        CHAR(16);      --流水号
BEGIN
  BEGIN
    SP_PB_SALECARD(P_ID,P_CARDNO,P_DEPOSIT,P_CARDCOST,P_OTHERFEE,P_CARDTRADENO,P_CARDTYPECODE,
                   P_CARDMONEY,P_SELLCHANNELCODE,P_SERSTAKETAG,P_TRADETYPECODE,P_CUSTNAME,
                   P_CUSTSEX,P_CUSTBIRTH,P_PAPERTYPECODE,P_PAPERNO,P_CUSTADDR,P_CUSTPOST,
                   P_CUSTPHONE,P_CUSTEMAIL,P_REMARK,P_CUSTRECTYPECODE,P_TERMNO,P_OPERCARDNO,
                   P_CURRENTTIME,P_SALECARDTRADEID,P_CURROPER,P_CURRDEPT,P_RETCODE,P_RETMSG);

     IF P_RETCODE != '0000000000' THEN RAISE V_EX; END IF;
        EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK; RETURN;
   END;

  -- 代理营业厅抵扣预付款，根据保证金修改可领卡额度，ADD BY LIUHE 20111230
  BEGIN
    SP_PB_DEPTBALFEE(P_SALECARDTRADEID, '3' ,--1预付款,2保证金,3预付款和保证金
           P_DEPOSIT + P_CARDCOST + P_OTHERFEE + P_CARDMONEY,
                   P_CURRENTTIME,P_CURROPER,P_CURRDEPT,P_RETCODE,P_RETMSG);

     IF P_RETCODE != '0000000000' THEN RAISE V_EX; END IF;
        EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK; RETURN;
   END;

   --调用休闲开通
	--获取流水号
    SP_GETSEQ(SEQ => V_SEQNO);

  --记录订单台帐表
    BEGIN
        INSERT INTO TF_B_ZZOL_SYN(
      TRADEID      , ORDERNO      ,DETAILNO    , TRADETYPECODE  ,SYNCTYPE	,
      UPDATEDEPARTID  , UPDATESTAFFNO    ,OPERATETIME )
    VALUES(
      V_SEQNO      ,ORDERNO      ,ORDERDETAILID    , '01'      , '01'		,
      P_CURRDEPT    , P_CURROPER    ,V_TODAY);
    IF SQL%ROWCOUNT != 1 THEN RAISE V_EX; END IF;
    EXCEPTION
    WHEN OTHERS THEN
            P_RETCODE := 'S094780092';
            P_RETMSG  := '记录订单台帐表失败'||SQLERRM;
            ROLLBACK; RETURN;
    END;

  P_RETCODE := '0000000000';
  P_RETMSG  := '';
  COMMIT; RETURN;
END;
/
