CREATE OR REPLACE PROCEDURE SP_GC_ZZUpdateSync
(
		P_TRADEID			VARCHAR2,		--交易流水号
		P_SYNCTYPE			CHAR,			--同步状态
		P_SYNCMSG			CHAR,			--同步信息
		
		
		P_CURROPER			CHAR,
		P_CURRDEPT			CHAR,
		P_RETCODE	        OUT CHAR, 		-- RETURN CODE
		P_RETMSG     	    OUT VARCHAR2	-- RETURN MESSAGE
)
AS
    V_EX          		EXCEPTION;
	V_ORDERCOUNT		INT;
	V_TODAY				DATE := SYSDATE;
    V_SEQNO				CHAR(16);			--流水号
BEGIN

	--更新同步信息表失败
	BEGIN
		UPDATE TF_F_ZZOL_SYNC 
			SET SYNCTYPE	= P_SYNCTYPE,
				SYNCMSG		= P_SYNCMSG
		WHERE	TRADEID	= P_TRADEID;
	   EXCEPTION
		  WHEN OTHERS THEN
			P_RETCODE := 'S094540109';
			P_RETMSG := '更新同步信息表失败' || SQLERRM;
		  ROLLBACK;RETURN;
	END;
   
	P_RETCODE := '0000000000';
	P_RETMSG  := '';
	COMMIT; RETURN;
END;

/

SHOW ERRORS

 