--------------------------------------------------
--  资源定义修改存储过程
--  初次编写
--  蒋兵兵
--  2012-12-06
--------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_RM_OTHER_ConditionModify
(
    P_RESOURCECODE      CHAR, 			--资源编码
    P_RESOURCENAME      CHAR,			--资源名称
	P_RESOURCETYPE		CHAR,			--资源类型
	P_DESCPIRTION		varchar2,		--资源描述
	P_ATTRIBUTE1		CHAR,			--属性1
	P_ATTRIBUTETYPE1	CHAR,			--属性1是否领用属性
	P_ATTRIBUTEISNULL1	CHAR,			--属性1是否必填
	P_ATTRIBUTE2		CHAR,			--属性2
	P_ATTRIBUTETYPE2	CHAR,			--属性2是否领用属性
	P_ATTRIBUTEISNULL2	CHAR,			--属性2是否必填
	P_ATTRIBUTE3		CHAR,			--属性3
	P_ATTRIBUTETYPE3	CHAR,			--属性3是否领用属性
	P_ATTRIBUTEISNULL3	CHAR,			--属性3是否必填
	P_ATTRIBUTE4		CHAR,			--属性4
	P_ATTRIBUTETYPE4	CHAR,			--属性4是否领用属性
	P_ATTRIBUTEISNULL4	CHAR,			--属性4是否必填
	P_ATTRIBUTE5		CHAR,			--属性5
	P_ATTRIBUTETYPE5	CHAR,			--属性5是否领用属性
	P_ATTRIBUTEISNULL5	CHAR,			--属性5是否必填
	P_ATTRIBUTE6		CHAR,			--属性6
	P_ATTRIBUTETYPE6	CHAR,			--属性6是否领用属性
	P_ATTRIBUTEISNULL6	CHAR,			--属性6是否必填
	
	P_CURROPER        CHAR,
    P_CURRDEPT        CHAR,
    p_retCode     out char, -- Return Code
    p_retMsg      out varchar2  -- Return Message
)
AS
    
    V_EXIST           INT     ;     --存在数量
    V_TODAY           DATE:=SYSDATE;
    V_EX              EXCEPTION;
	
BEGIN
	--验证资源编码在库中是否存在
	
	SELECT COUNT(*) INTO v_exist FROM  TD_M_RESOURCE WHERE RESOURCENAME = P_RESOURCENAME  AND RESOURCECODE!= P_RESOURCECODE;
		IF v_exist > 0 THEN
			P_RETCODE := 'A001002106';
			P_RETMSG  := '已有此资源名称存在于库中';
			ROLLBACK; RETURN;
		END IF;
	
	--验证此资源是否已经下单
		SELECT  COUNT(*) INTO v_exist FROM  TF_F_RESOURCEAPPLYORDER WHERE RESOURCECODE = P_RESOURCECODE;
		IF v_exist > 0 THEN
			P_RETCODE := 'A001002107';
			P_RETMSG  := '此资源已下单,无法执行修改操作';
		ROLLBACK; RETURN;
		END IF;
	
	--修改资源表
	BEGIN
		
		UPDATE   TD_M_RESOURCE A																														
		SET     A.RESOURCENAME =P_RESOURCENAME, A.RESOURCETYPE =P_RESOURCETYPE,A.DESCPIRTION= P_DESCPIRTION,																														
				A.ATTRIBUTE1=P_ATTRIBUTE1,  A.ATTRIBUTETYPE1=P_ATTRIBUTETYPE1, A.ATTRIBUTEISNULL1=P_ATTRIBUTEISNULL1, 																												
				A.ATTRIBUTE2=P_ATTRIBUTE2,  A.ATTRIBUTETYPE2=P_ATTRIBUTETYPE2, A.ATTRIBUTEISNULL2=P_ATTRIBUTEISNULL2, 																												
				A.ATTRIBUTE3=P_ATTRIBUTE3,  A.ATTRIBUTETYPE3=P_ATTRIBUTETYPE3, A.ATTRIBUTEISNULL3=P_ATTRIBUTEISNULL3, 																												
				A.ATTRIBUTE4=P_ATTRIBUTE4,  A.ATTRIBUTETYPE4=P_ATTRIBUTETYPE4, A.ATTRIBUTEISNULL4=P_ATTRIBUTEISNULL4, 																												
				A.ATTRIBUTE5=P_ATTRIBUTE5,  A.ATTRIBUTETYPE5=P_ATTRIBUTETYPE5, A.ATTRIBUTEISNULL5=P_ATTRIBUTEISNULL5, 																												
				A.ATTRIBUTE6=P_ATTRIBUTE6,  A.ATTRIBUTETYPE6=P_ATTRIBUTETYPE6, A.ATTRIBUTEISNULL6=P_ATTRIBUTEISNULL6, 																												
				A.UPDATESTAFFNO=P_CURROPER ,A.UPDATETIME=V_TODAY																												
		WHERE	A.RESOURCECODE=P_RESOURCECODE;																												

		IF  SQL%ROWCOUNT != 1 THEN RAISE V_EX; END IF;
				  EXCEPTION
					WHEN OTHERS THEN
					  P_RETCODE := 'S001002106';
					  P_RETMSG  := '更新资源表失败'||SQLERRM;
					  ROLLBACK; RETURN;
	END;
	
	p_retCode := '0000000000';
	p_retMsg  := '';
	COMMIT; RETURN;   
END;

/
show errors


