--------------------------------------------------
--  资源定义添加存储过程
--  初次编写
--  蒋兵兵
--  2012-12-06
--------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_RM_OTHER_ConditionAdd
(
    P_RESOURCECODE      CHAR, 			--资源编码
    P_RESOURCENAME      CHAR,			--资源名称
	P_RESOURCETYPE		CHAR,			--资源类型
	P_DESCPIRTION		varchar2,		--资源描述
	P_ATTRIBUTE1		CHAR,			--属性1
	P_ATTRIBUTETYPE1	CHAR,			--属性1是否领用属性
	P_ATTRIBUTEISNULL1	CHAR,			--属性1是否必填
	P_ATTRIBUTE2		CHAR,			--属性2
	P_ATTRIBUTETYPE2	CHAR,			--属性2是否领用属性
	P_ATTRIBUTEISNULL2	CHAR,			--属性2是否必填
	P_ATTRIBUTE3		CHAR,			--属性3
	P_ATTRIBUTETYPE3	CHAR,			--属性3是否领用属性
	P_ATTRIBUTEISNULL3	CHAR,			--属性3是否必填
	P_ATTRIBUTE4		CHAR,			--属性4
	P_ATTRIBUTETYPE4	CHAR,			--属性4是否领用属性
	P_ATTRIBUTEISNULL4	CHAR,			--属性4是否必填
	P_ATTRIBUTE5		CHAR,			--属性5
	P_ATTRIBUTETYPE5	CHAR,			--属性5是否领用属性
	P_ATTRIBUTEISNULL5	CHAR,			--属性5是否必填
	P_ATTRIBUTE6		CHAR,			--属性6
	P_ATTRIBUTETYPE6	CHAR,			--属性6是否领用属性
	P_ATTRIBUTEISNULL6	CHAR,			--属性6是否必填
	
	P_CURROPER        CHAR,
    P_CURRDEPT        CHAR,
    p_retCode     out char, -- Return Code
    p_retMsg      out varchar2  -- Return Message
)
AS
    
    V_EXIST           INT     ;     --存在数量
    V_TODAY           DATE:=SYSDATE;
    V_EX              EXCEPTION;
	
BEGIN
	--验证资源编码在库中是否存在
	
	SELECT count(*) INTO v_exist FROM  TD_M_RESOURCE WHERE RESOURCECODE = P_RESOURCECODE;
		IF v_exist > 0 THEN
			P_RETCODE := 'A094780195';
			P_RETMSG  := '已有此资源编码存在于库中';
			ROLLBACK; RETURN;
		END IF;
	
	--验证资源名称在库中是否存在
		SELECT count(*) INTO v_exist FROM  TD_M_RESOURCE WHERE RESOURCENAME = P_RESOURCENAME;
		IF v_exist > 0 THEN
			P_RETCODE := 'A094780194';
			P_RETMSG  := '已有此资源名称存在于库中';
		ROLLBACK; RETURN;
		END IF;
	
	--记录资源表
	BEGIN
		
		INSERT INTO TD_M_RESOURCE(
		RESOURCECODE     , RESOURCENAME    , RESOURCETYPE     , DESCPIRTION     , ATTRIBUTE1     , ATTRIBUTETYPE1    , ATTRIBUTEISNULL1,
		ATTRIBUTE2       ,ATTRIBUTETYPE2   , ATTRIBUTEISNULL2 , ATTRIBUTE3      , ATTRIBUTETYPE3 , ATTRIBUTEISNULL3  , ATTRIBUTE4      ,
		ATTRIBUTETYPE4 , ATTRIBUTEISNULL4  , ATTRIBUTE5      ,ATTRIBUTETYPE5 , ATTRIBUTEISNULL5  , ATTRIBUTE6      ,ATTRIBUTETYPE6 		,
		ATTRIBUTEISNULL6 ,UPDATESTAFFNO    , UPDATETIME)
		VALUES(
		P_RESOURCECODE    , P_RESOURCENAME   , P_RESOURCETYPE     , P_DESCPIRTION    , P_ATTRIBUTE1     , P_ATTRIBUTETYPE1   ,P_ATTRIBUTEISNULL1,
		P_ATTRIBUTE2      ,P_ATTRIBUTETYPE2  , P_ATTRIBUTEISNULL2 , P_ATTRIBUTE3     , P_ATTRIBUTETYPE3 , P_ATTRIBUTEISNULL3  , P_ATTRIBUTE4   ,
		P_ATTRIBUTETYPE4 , P_ATTRIBUTEISNULL4  , P_ATTRIBUTE5   ,P_ATTRIBUTETYPE5 , P_ATTRIBUTEISNULL5  , P_ATTRIBUTE6   ,P_ATTRIBUTETYPE6 		,
		P_ATTRIBUTEISNULL6 ,P_CURROPER  , V_TODAY); 
		IF  SQL%ROWCOUNT != 1 THEN RAISE V_EX; END IF;
				  EXCEPTION
					WHEN OTHERS THEN
					  P_RETCODE := 'S001002104';
					  P_RETMSG  := '记录资源表失败'||SQLERRM;
					  ROLLBACK; RETURN;
	END;
	
	--记录库存汇总表
	BEGIN
		INSERT INTO  TL_R_RESOURCESUM(																					
		RESOURCECODE    , INSNUM        , USENUM        ,UPDATESTAFFNO  ,UPDATETIME  )
		VALUES(
		P_RESOURCECODE  , 0             ,0              ,P_CURROPER     ,V_TODAY    );
		IF  SQL%ROWCOUNT != 1 THEN RAISE V_EX; END IF;
				  EXCEPTION
					WHEN OTHERS THEN
					  P_RETCODE := 'S001002105';
					  P_RETMSG  := '记录库存汇总表失败'||SQLERRM;
					  ROLLBACK; RETURN;
	END;
	p_retCode := '0000000000';
	p_retMsg  := '';
	COMMIT; RETURN;   
END;

/
show errors


