  -- =============================================
  -- AUTHOR:    LIUHE 
  -- CREATE DATE: 2011-12-28
  -- DESCRIPTION:  网点结算单元佣金方案增删改
  -- MODIFY: 
  -- =============================================
CREATE OR REPLACE PROCEDURE SP_PS_DEPTBALCOMSCHEME 
(
	P_BALUNITNO     CHAR,
	P_COMSCHEMENO   CHAR,
	P_TRADETYPECODE CHAR,
	P_CANCELTRADE   CHAR,
	P_BEGINTIME     CHAR, --YYYY-MM-DD HH24:MI:SS
	P_ENDTIME       CHAR,
	P_BALCOMSID   	CHAR,
	P_OPTYPE        CHAR,
	P_CURROPER CHAR,
	P_CURRDEPT CHAR,
	P_RETCODE  OUT CHAR,
	P_RETMSG   OUT VARCHAR2
)
AS
  V_CURRDATE  DATE := SYSDATE;
  V_SEQNO     CHAR(16);
  V_DTRADETYPECODE CHAR(2);
  V_BALCOMSID CHAR(8);
  V_COUNT 	  INT;

BEGIN
	
	
	IF P_OPTYPE = 'ADD' THEN 
		V_DTRADETYPECODE :='21';
		SP_GETBIZAPPCODE(1, 'D2', 8, V_BALCOMSID);
	ELSIF  P_OPTYPE = 'MODIFY' THEN 
		V_DTRADETYPECODE :='22';V_BALCOMSID :=P_BALCOMSID;
	ELSIF P_OPTYPE = 'DEL' THEN 
		V_DTRADETYPECODE :='23';V_BALCOMSID :=P_BALCOMSID;
	END IF; 
	
	
	IF P_OPTYPE = 'ADD' OR P_OPTYPE = 'MODIFY' THEN 
		--判断当前业务是否存在时间重叠的佣金方案,待审批
		SELECT	COUNT(*) INTO V_COUNT
		FROM  TF_B_DEPTBALTRADE B, TH_DEPTBAL_COMSCHEME T
		WHERE B.TRADEID = T.TRADEID
			AND  B.STATECODE = '1'
			AND (	
				T.BEGINTIME <= TO_DATE(P_BEGINTIME,'yyyy-MM-dd hh24:mi:ss')  AND T.ENDTIME >= TO_DATE(P_ENDTIME,'yyyy-MM-dd hh24:mi:ss')
				OR 
				T.BEGINTIME >= TO_DATE(P_BEGINTIME,'yyyy-MM-dd hh24:mi:ss')  AND T.BEGINTIME <=TO_DATE(P_ENDTIME,'yyyy-MM-dd hh24:mi:ss')
				OR 
				T.ENDTIME >= TO_DATE(P_BEGINTIME,'yyyy-MM-dd hh24:mi:ss')  AND T.ENDTIME <=TO_DATE(P_ENDTIME,'yyyy-MM-dd hh24:mi:ss')
			)
			AND  T.DBALUNITNO  =  P_BALUNITNO 
			AND  T.TRADETYPECODE = P_TRADETYPECODE; 

		IF V_COUNT > 0 THEN
				p_retCode := 'S008107911';
				p_retMsg  := '所选结算单元的当前业务已有时间重叠的佣金方案为待审批状态';
				RETURN;
		END IF;

		--判断当前业务是否存在时间重叠的佣金方案,待审核
		SELECT	COUNT(*) INTO V_COUNT
		FROM  TF_B_DEPTBALTRADE_EXAM E, TH_DEPTBAL_COMSCHEME T
		WHERE E.TRADEID = T.TRADEID
			AND  E.STATECODE = '1'
			AND (	
				T.BEGINTIME<=TO_DATE(P_BEGINTIME,'yyyy-MM-dd hh24:mi:ss')  AND T.ENDTIME >=TO_DATE(P_ENDTIME,'yyyy-MM-dd hh24:mi:ss')
				OR 
				T.BEGINTIME >=TO_DATE(P_BEGINTIME,'yyyy-MM-dd hh24:mi:ss')  AND T.BEGINTIME <=TO_DATE(P_ENDTIME,'yyyy-MM-dd hh24:mi:ss')
				OR 
				T.ENDTIME >=TO_DATE(P_BEGINTIME,'yyyy-MM-dd hh24:mi:ss')  AND T.ENDTIME <=TO_DATE(P_ENDTIME,'yyyy-MM-dd hh24:mi:ss')
			)
			AND  T.DBALUNITNO  =  P_BALUNITNO
			AND  T.TRADETYPECODE = P_TRADETYPECODE;

		IF V_COUNT > 0 THEN
					 p_retCode := 'S008107912';
				p_retMsg  := '所选结算单元的当前业务已有时间重叠的佣金方案为待审核状态';
				RETURN;
		END IF;
		
	END IF ;
	
	--判断当前业务是否存在时间重叠的佣金方案,财审通过
	IF P_OPTYPE = 'ADD' THEN 
		SELECT	COUNT(*) INTO V_COUNT
		FROM 	TD_DEPTBAL_COMSCHEME T
		WHERE	T.DBALUNITNO = P_BALUNITNO
				AND (	
						T.BEGINTIME<=TO_DATE(P_BEGINTIME,'yyyy-MM-dd hh24:mi:ss')  AND T.ENDTIME >=TO_DATE(P_ENDTIME,'yyyy-MM-dd hh24:mi:ss')
						OR 
						T.BEGINTIME >=TO_DATE(P_BEGINTIME,'yyyy-MM-dd hh24:mi:ss')  AND T.BEGINTIME <=TO_DATE(P_ENDTIME,'yyyy-MM-dd hh24:mi:ss')
						OR 
						T.ENDTIME >=TO_DATE(P_BEGINTIME,'yyyy-MM-dd hh24:mi:ss')  AND T.ENDTIME <=TO_DATE(P_ENDTIME,'yyyy-MM-dd hh24:mi:ss')
					)
			  AND T.USETAG = '1' AND  T.TRADETYPECODE = P_TRADETYPECODE; 

		IF V_COUNT > 0 THEN
				p_retCode := 'S008107913';
				p_retMsg  := '所选结算单元的当前业务已有时间重叠的佣金方案';
				RETURN;
		END IF;
	END IF ;
	
  --2) GET THE SEQUENCE NUMBER
  SP_GETSEQ(SEQ => V_SEQNO);


  --3) ADD MAIN LOG INFO
  BEGIN
    INSERT INTO TF_B_DEPTBALTRADE
      (TRADEID,
       DTRADETYPECODE,
       ASSOCIATECODE,
       OPERATESTAFFNO,
       OPERATEDEPARTID,
       OPERATETIME,
       STATECODE)
    VALUES
      (V_SEQNO, V_DTRADETYPECODE, P_BALUNITNO, P_CURROPER, P_CURRDEPT, V_CURRDATE, '1');

  EXCEPTION
    WHEN OTHERS THEN
      P_RETCODE := 'S008107071';
      P_RETMSG  := '记录台账信息失败' || SQLERRM;
      ROLLBACK;
      RETURN;
  END;

  --4) ADD ADDITIONAL LOG INFO  INTO TF_TBALUNIT_COMSCHEMECHANGE
  BEGIN
    INSERT INTO TH_DEPTBAL_COMSCHEME
      (TRADEID,
	   ID,
       DCOMSCHEMENO,
       DBALUNITNO,
       TRADETYPECODE,
       CANCELTRADE,
       BEGINTIME,
       ENDTIME)
    VALUES
      (V_SEQNO,
	   V_BALCOMSID,
       P_COMSCHEMENO,
       P_BALUNITNO,
       P_TRADETYPECODE,
	   P_CANCELTRADE,
       TO_DATE(P_BEGINTIME, 'YYYY-MM-DD HH24:MI:SS'),
       TO_DATE(P_ENDTIME, 'YYYY-MM-DD HH24:MI:SS'));

  EXCEPTION
    WHEN OTHERS THEN
      P_RETCODE := 'S008107072';
      P_RETMSG  := '记录网点结算单元佣金方案历史表失败'|| SQLERRM;
      ROLLBACK;
      RETURN;
  END;

  --5) ADD ADDITIONAL LOG INFO  INTO TF_B_TRADE_BALUNITCHANGE
  BEGIN
    INSERT INTO TH_DEPT_BALUNIT
      (TRADEID ,
      DBALUNITNO,
       DBALUNIT,
       BANKCODE,
       BANKACCNO,
       CREATETIME,
       BALCYCLETYPECODE,
       BALINTERVAL,
       FINCYCLETYPECODE,
       FININTERVAL,
       FINTYPECODE,
       FINBANKCODE,
       LINKMAN,
       UNITPHONE,
       UNITADD,
       UNITEMAIL,
       USETAG,
       DEPTTYPE,
       PREPAYWARNLINE,
       PREPAYLIMITLINE,
       UPDATESTAFFNO,
       UPDATETIME,
       REMARK)
      SELECT V_SEQNO,
             DBALUNITNO,
             DBALUNIT,
             BANKCODE,
             BANKACCNO,
             CREATETIME,
             BALCYCLETYPECODE,
             BALINTERVAL,
             FINCYCLETYPECODE,
             FININTERVAL,
             FINTYPECODE,
             FINBANKCODE,
             LINKMAN,
             UNITPHONE,
             UNITADD,
             UNITEMAIL,
             USETAG,
             DEPTTYPE,
             PREPAYWARNLINE,
             PREPAYLIMITLINE,
             UPDATESTAFFNO,
             UPDATETIME,
             REMARK
        FROM TF_DEPT_BALUNIT
       WHERE DBALUNITNO = P_BALUNITNO;

  EXCEPTION
    WHEN OTHERS THEN
      P_RETCODE := 'S008107082';
      P_RETMSG  := '写入网点结算单元变历史表失败' || SQLERRM;
      ROLLBACK;
      RETURN;
  END;

  P_RETCODE := '0000000000';
  P_RETMSG  := '';
  COMMIT;
  RETURN;
END;



/

  SHOW ERRORS
