CREATE OR REPLACE SYNONYM SP_OA_CardVerify FOR cc.SP_OA_CardVerify
/

@SP_OA_SelectRandom.sql
@SP_OA_SelectSam.sql
@SP_OA_DeleteRandom.sql
@SP_OA_CreateRandom.sql
@SP_GetBizAppCode_PL.sql
@SP_GetSeq_PL.sql
@SP_OA_TradeCancel.sql
@SP_AccCheck_PL.sql
@SP_OA_AccCheckAsn.sql
@SP_OA_GroupVerify.sql
@SP_OA_CardCommitEX.sql
@SP_OA_CardCommit.sql
@SP_OA_GroupCommit.sql
@SP_OA_GroupChangePass.sql
@SP_OA_TradeSell.sql
@SP_OA_SupplyCommit.sql
@SP_OA_TradeLoad.sql