/*
*验证卡片代理充值上限
*add by liuhe20121113
*/
CREATE OR REPLACE PROCEDURE SP_ProxyChargeLimit
(
	P_CARDNO	  	CHAR, --充值卡号
	P_CHARGEDATE 	DATE, --充值日期
	P_CARDTRADENO	CHAR, --充值交易序号
	P_TRADEMONEY	INT,  --充值金额
	P_CHARGECHANNEL CHAR, --预留,01 TF_OUTSUPPLY_COMMIT TUXEDO代理，02 TF_SUPPLY_REALTIME 前台业务系统代理
	P_CURROPER		CHAR,
	P_CURRDEPT		CHAR,
	P_RETCODE	  	OUT CHAR, -- RETURN CODE
	P_RETMSG 	  	OUT VARCHAR2  -- RETURN MESSAGE
)
AS
	V_COUNT				INT;
	V_SUPPLYMONEY		INT;--存放单卡同日前台代理已充值金额
	V_TAGMONEY			INT;
	V_EX                EXCEPTION;
BEGIN	
	-----判断是否配置了充值限制
	SELECT COUNT(*) INTO V_COUNT 
	FROM TD_M_TAG  WHERE TAGCODE='PROXY_CHARGE_LIMIT' AND USETAG='1';
	
	IF V_COUNT = 1 THEN
			
			--查询当日当卡TF_SUPPLY_REALTIME表的充值总额
			SELECT 	NVL(SUM(T.TRADEMONEY),0) INTO V_SUPPLYMONEY
			FROM 	TF_SUPPLY_REALTIME T, TD_M_INSIDESTAFF S, TD_DEPTBAL_RELATION R, TF_DEPT_BALUNIT B
			WHERE 	T.OPERATESTAFFNO = S.STAFFNO AND S.DEPARTNO = R.DEPARTNO AND B.DBALUNITNO = R.DBALUNITNO
					AND R.USETAG='1' AND B.DEPTTYPE = '1'  AND T.CARDNO = P_CARDNO 
					AND T.TRADETYPECODE IN ('02','B1')
					AND T.TRADEDATE = TO_CHAR(P_CHARGEDATE,'YYYYMMDD')
					AND S.DEPARTNO = P_CURRDEPT;
			
			--查询充值限额
			SELECT TAGVALUE INTO V_TAGMONEY FROM TD_M_TAG WHERE TAGCODE='PROXY_CHARGE_LIMIT' AND USETAG='1';
			
			---如果当卡当日在当代理点代理充值总额超过配置的上限则提示错误
			IF V_SUPPLYMONEY + P_TRADEMONEY> V_TAGMONEY THEN 
				P_RETCODE := 'A009010091';
				P_RETMSG := '在代理机构单张卡同日累计充值不能超过'||V_TAGMONEY/100.00||'元';
				RETURN;
			END IF;
			
	END IF;

	P_RETCODE := '0000000000';
	P_RETMSG  := '';

  END;  
  
  
/

SHOW ERRORS

