CREATE OR REPLACE SYNONYM SP_PB_XFCommit FOR cc.SP_PB_XFCommit
/

@SP_PB_UpdateAcc_PL.sql   
@SP_PB_CreateTmp_PL.sql 
@SP_PB_SaleCardRollback_PL.sql       
@SP_PB_ReadRecord_PL.sql             
@SP_PB_XFCharge_PL.sql               
@SP_PB_SaleCard_PL.sql               
@SP_PB_ChangeCardRollback_PL.sql     
@SP_PB_UnLoad_PL.sql                 
@SP_PB_Unlock_PL.sql                 
@SP_PB_Refund_PL.sql                 
@SP_PB_Retrade_PL.sql                
@SP_PB_ReturnCardRollback_PL.sql     
@SP_PB_Speloadcancel_PL.sql                                  
@SP_PB_Speloadinput_PL.sql                      
@SP_PB_BadCard_PL.sql                           
@SP_PB_Charge_PL.sql                            
@SP_PB_Speload_PL.sql                                   
@SP_PB_ChangeUserInfo_PL.sql                    
@SP_PB_ChangeCard_PL.sql                        
@SP_PB_ReturnCard_PL.sql                        
@SP_PB_Destroy_PL.sql                           
@SP_PB_Recover_PL.sql                           
@SP_PB_TransitBalance_PL.sql  
@SP_PB_ChangeCard_COMMIT_PL.sql  
@SP_PB_ChangeCardRollback_COM_PL.sql 
@SP_PB_SaleCardRollback_COMMIT_PL.sql 
@SP_PB_SaleCard_COMMIT_PL.sql                  

                                                                                                          
                                                                                        
                                                                                        
                                                                                        
                                                                                        
                                                                                        
                                                                                        
                                                                                        
                                                                                        
                                                                                        
                                                                                        
                                                                                        

