CREATE OR REPLACE PROCEDURE SP_WA_LRTBlackListADD
(
    P_CARDNO        CHAR    ,
    P_OVERTIMEMONEY INT     ,
    P_REMARK        VARCHAR2,
    P_LISTTYPECODE  CHAR,

    P_CURROPER     CHAR    ,
    P_CURRDEPT     CHAR    ,
    P_RETCODE  OUT CHAR    ,
    P_RETMSG   OUT VARCHAR2
)
AS
    V_INT          INT;
    V_TODAY        DATE := SYSDATE;
BEGIN

    -- 新增黑名单
  BEGIN
    INSERT INTO TF_B_WARN_BLACK
        (CARDNO, CREATETIME, WARNTYPE, WARNLEVEL,
        UPDATESTAFFNO, UPDATETIME, DOWNTIME, REMARK,
        BLACKSTATE, BLACKTYPE, BLACKLEVEL, OVERTIMEMONEY,LISTTYPECODE)
    VALUES
        (P_CARDNO, V_TODAY, NULL, '1',
        P_CURROPER, V_TODAY, NULL, P_REMARK,
        '0', '3', '0', P_OVERTIMEMONEY,P_LISTTYPECODE);

    EXCEPTION
          WHEN OTHERS THEN
              P_RETCODE := 'S002W01001';
              P_RETMSG  := '新增黑名单表失败' || SQLERRM;
              ROLLBACK; RETURN;
    END;

    -- 生成备份台账
  BEGIN
    INSERT INTO TH_B_WARN_BLACK
    (HSEQNO, BACKTIME, BACKSTAFF, BACKWHY,
    CARDNO, CREATETIME, WARNTYPE, WARNLEVEL,
    UPDATESTAFFNO, UPDATETIME, DOWNTIME, REMARK,
    BLACKSTATE, BLACKTYPE, BLACKLEVEL, OVERTIMEMONEY,LISTTYPECODE)
    SELECT
        TH_B_WARN_BLACK_SEQ.NEXTVAL, V_TODAY, P_CURROPER,  '5',
        CARDNO, CREATETIME, WARNTYPE, WARNLEVEL,
        UPDATESTAFFNO, UPDATETIME, DOWNTIME, REMARK,
        BLACKSTATE, BLACKTYPE, BLACKLEVEL,OVERTIMEMONEY,P_LISTTYPECODE
    FROM     TF_B_WARN_BLACK
    WHERE     CARDNO = P_CARDNO;


    EXCEPTION
          WHEN OTHERS THEN
              P_RETCODE := 'S002W01002';
              P_RETMSG  := '新增黑名单备份表失败' || SQLERRM;
              ROLLBACK; RETURN;
    END;

  P_RETCODE := '0000000000';
  P_RETMSG  := '';
  COMMIT; RETURN;

END;
/
show errors


			
