CREATE OR REPLACE PROCEDURE SP_WA_LRTBlackListDEL
(
    P_CARDNO        CHAR    ,

    P_CURROPER     CHAR    ,
    P_CURRDEPT     CHAR    ,
    P_RETCODE  OUT CHAR    ,
    P_RETMSG   OUT VARCHAR2
)
AS
    V_INT          INT;
    V_TODAY        DATE := SYSDATE;
  V_EX           EXCEPTION;
BEGIN

    -- 生成备份台账
  BEGIN
    INSERT INTO TH_B_WARN_BLACK
    (HSEQNO, BACKTIME, BACKSTAFF, BACKWHY,
    CARDNO, CREATETIME, WARNTYPE, WARNLEVEL,
    UPDATESTAFFNO, UPDATETIME, DOWNTIME, REMARK,
    BLACKSTATE, BLACKTYPE, BLACKLEVEL,OVERTIMEMONEY)
    SELECT
        TH_B_WARN_BLACK_SEQ.NEXTVAL, V_TODAY, P_CURROPER, '5',
        CARDNO, CREATETIME, WARNTYPE, WARNLEVEL,
        UPDATESTAFFNO, UPDATETIME, DOWNTIME, REMARK,
        BLACKSTATE, BLACKTYPE, BLACKLEVEL,OVERTIMEMONEY
    FROM     TF_B_WARN_BLACK
    WHERE     CARDNO = P_CARDNO;


    EXCEPTION
          WHEN OTHERS THEN
              P_RETCODE := 'S002W01003';
              P_RETMSG  := '新增黑名单备份表失败' || SQLERRM;
              ROLLBACK; RETURN;
    END;

    -- 删除黑名单
  BEGIN
    DELETE FROM TF_B_WARN_BLACK
    WHERE  CARDNO = P_CARDNO;

    IF  SQL%ROWCOUNT != 1 THEN RAISE v_ex; END IF;

    EXCEPTION
          WHEN OTHERS THEN
              P_RETCODE := 'S002W01004';
              P_RETMSG  := '删除黑名单失败' || SQLERRM;
              ROLLBACK; RETURN;
    END;

  P_RETCODE := '0000000000';
  P_RETMSG  := '';
  COMMIT; RETURN;

END;
/
show errors


			
