CREATE OR REPLACE PROCEDURE SP_WA_GrayListADD
(
    P_CARDNO        CHAR    ,
    P_REMARK        VARCHAR2,

    P_CURROPER     CHAR    ,
    P_CURRDEPT     CHAR    ,
    P_RETCODE  OUT CHAR    ,
    P_RETMSG   OUT VARCHAR2
)
AS
    V_INT          INT;
    V_TODAY        DATE := SYSDATE;
BEGIN

    -- 新增灰名单
  BEGIN
    INSERT INTO TF_B_WARN_GRAY
        (CARDNO			, CREATETIME	, WARNTYPE	, WARNLEVEL		,
        UPDATESTAFFNO	, UPDATETIME	, DOWNTIME	, REMARK		,
        GRAYSTATE		, GRAYTYPE		, GRAYLEVEL	, OVERTIMEMONEY	,
		CITYCODE)
    VALUES
        (P_CARDNO		, V_TODAY		, NULL		, '1'			,
        P_CURROPER		, V_TODAY		, NULL		, P_REMARK		,
        '0'				, '0'			, '0'		, 0				,
		'2150');

    EXCEPTION
          WHEN OTHERS THEN
              P_RETCODE := 'S002W01089';
              P_RETMSG  := '新增灰名单表失败' || SQLERRM;
              ROLLBACK; RETURN;
    END;

    -- 生成备份台账
  BEGIN
    INSERT INTO TH_B_WARN_GRAY
    (HSEQNO			, BACKTIME		, BACKSTAFF		, BACKWHY		,
	CARDNO			, CREATETIME	, WARNTYPE		, WARNLEVEL		,
    UPDATESTAFFNO	, UPDATETIME	, DOWNTIME		, REMARK		,
    GRAYSTATE		, GRAYTYPE		, GRAYLEVEL		, OVERTIMEMONEY ,
	CITYCODE)
    SELECT
	TH_B_WARN_GRAY_SEQ.NEXTVAL, V_TODAY, P_CURROPER	,  '5'			,
	CARDNO			, CREATETIME	, WARNTYPE		, WARNLEVEL		,
	UPDATESTAFFNO	, UPDATETIME	, DOWNTIME		, REMARK		,
	GRAYSTATE		, GRAYTYPE		, GRAYLEVEL		,OVERTIMEMONEY	,
	CITYCODE
    FROM	TF_B_WARN_GRAY
    WHERE	CARDNO = P_CARDNO;


    EXCEPTION
          WHEN OTHERS THEN
              P_RETCODE := 'S002W01090';
              P_RETMSG  := '新增灰名单备份表失败' || SQLERRM;
              ROLLBACK; RETURN;
    END;

  P_RETCODE := '0000000000';
  P_RETMSG  := '';
  COMMIT; RETURN;

END;
/
show errors


			
