/*
create time:2014/9/15
creator:dongx
content:区分备付金、自有资金、押金
*/
CREATE OR REPLACE FUNCTION FUN_GETBFJTRADETYPE
(TRADETYPECODE IN CHAR, 
BFJTRADETYPE IN CHAR)  --01：营业厅日报备付金 02: 代理营业厅备付金 03: 订单备付金
  RETURN CHAR AS
  v_result CHAR(2);
BEGIN
  v_result := '01';
  --押金： 旅游卡售卡
  IF TRADETYPECODE = '7H' OR TRADETYPECODE = '7R' OR TRADETYPECODE = 'M3'  THEN 
	   IF BFJTRADETYPE = '01' THEN 
		 v_result := '15'; 
	   ELSIF BFJTRADETYPE = '02' THEN 
	     v_result := '11';  
	   ELSIF BFJTRADETYPE = '03' THEN 
		 v_result := '13';
	   END IF;
  --备付金： 充值 专有账户充值 礼金卡售卡 换乘抽奖奖励
  ELSIF TRADETYPECODE = '02' OR TRADETYPECODE = 'B1' OR TRADETYPECODE = '8Q' OR  TRADETYPECODE = '8Z'
       OR  TRADETYPECODE = '16' OR  TRADETYPECODE = 'L2' OR  TRADETYPECODE = '8Y' OR  TRADETYPECODE = '8L'
	   OR  TRADETYPECODE = '50' OR  TRADETYPECODE ='F0'  OR  TRADETYPECODE = '51' OR  TRADETYPECODE = 'F1'
	   OR TRADETYPECODE = 'M1' THEN  
		 v_result := BFJTRADETYPE;  
  -- 自有资金
  ELSIF (TRADETYPECODE != '02' AND TRADETYPECODE != 'B1' AND TRADETYPECODE != '8Q' AND  TRADETYPECODE != '8Z'
       AND  TRADETYPECODE != '16' AND  TRADETYPECODE != 'L2' AND  TRADETYPECODE != '8Y' AND  TRADETYPECODE != '8L'
	   AND  TRADETYPECODE != '50' AND  TRADETYPECODE != 'F0'  AND TRADETYPECODE != '51' AND  TRADETYPECODE != 'F1' 
	   AND  TRADETYPECODE != '7H'  AND TRADETYPECODE != '7R') OR  TRADETYPECODE = 'M2'THEN
       IF BFJTRADETYPE = '01' THEN 
		 v_result := '14'; 
	   ELSIF BFJTRADETYPE = '02' THEN 
	     v_result := '10';  
	   ELSIF BFJTRADETYPE = '03' THEN 
		 v_result := '12';
	   END IF;
  END IF; 
  RETURN v_result;
END FUN_GETBFJTRADETYPE;
/
