CREATE OR REPLACE FUNCTION FUN_GETBFJTRADEID(TRADEDATE IN CHAR)
	RETURN VARCHAR2 AS
	v_result CHAR(16);
BEGIN
	SELECT TRADEDATE || SUBSTR('00000000' || TO_CHAR(TF_F_BFJ_TRADERECORD_SEQ.NEXTVAL), -8)
	INTO v_result
	FROM dual;
	RETURN v_result;
END FUN_GETBFJTRADEID;
/
