/*
create time:2014/8/8
creator:dongx
content:生成备付金报表数据 
update: 20140918 备付金 自有资金 押金分开取数 
update：20140924 期初数据取不到时，取0
update：20141124 若干取数规则变更
update: 20141128 若干规则变更
UPDATE: 20141202 10月调平版本
*/

CREATE OR REPLACE PROCEDURE SP_BFJ_GenerateReportData
(
  p_tradeDate  char,        -- 日期 格式YYYYMMDD
  p_currOper  char,           -- 操作员工
  p_currDept  char,        -- 操作部门
    p_retCode    out char,     -- Return Code
    p_retMsg     out varchar2   -- Return Message
)
as
  v_now            date := sysdate;  --当前时间
  v_F1           NUMBER(12,6);
  v_F2           NUMBER(12,6);
  v_money        NUMBER(12,6);
  v_isReport     char(1);
  v_lastInMatchDate char(8);
  v_lastOutMatchdate char(8);
BEGIN


  
  --查询备付金任务表
  BEGIN
    SELECT ISREPORT  INTO v_isReport FROM TF_F_BFJ_TASK WHERE BFJDATE = p_tradeDate AND ISINMATCH = '1' AND ISOUTMATCH = '1';
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005001';
      p_retMsg  := p_tradeDate || '没有确认出入金';
      ROLLBACK; RETURN;
  END;
  
  --最后确认完成入金日期
  BEGIN
	  SELECT BFJDATE INTO v_lastInMatchDate FROM (
	  SELECT BFJDATE FROM TF_F_BFJ_TASK WHERE ISINMATCH = '1' 
	  AND BFJDATE >= TO_CHAR(trunc(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
	  AND BFJDATE <= TO_CHAR(LAST_DAY(TO_DATE(p_tradeDate,'yyyyMMdd')))
	  ORDER BY BFJDATE DESC) WHERE ROWNUM = 1; 
	 EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005101';
      p_retMsg  := '最后确认完成入金日期查询失败';
      ROLLBACK; RETURN;
  END;
  
  --最后确认完成出金日期
  BEGIN
	  SELECT BFJDATE INTO v_lastOutMatchDate FROM (
	  SELECT BFJDATE FROM TF_F_BFJ_TASK WHERE ISOUTMATCH = '1' 
	  AND BFJDATE >= TO_CHAR(trunc(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
	  AND BFJDATE <= TO_CHAR(LAST_DAY(TO_DATE(p_tradeDate,'yyyyMMdd')))
	  ORDER BY BFJDATE DESC) WHERE ROWNUM = 1; 
	 EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005102';
      p_retMsg  := '最后确认完成出金日期询失败';
      ROLLBACK; RETURN;
  END;

  IF v_isReport = 1 THEN
  --删除所有报表
  BEGIN
    DELETE TF_F_BFJ_REPORT1 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT2 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT3 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT4 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT5 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT6 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT7 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT8 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT9 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT10 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT11 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT12 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT13 WHERE BFJDATE = p_tradeDate;
    DELETE TF_F_BFJ_REPORT2_1 WHERE BFJDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005002';
      p_retMsg  := '删除报表数据错误'|| SQLERRM;
      ROLLBACK; RETURN;
  END;
  ELSE
    --执行旧备付金计算存储过程 
  BEGIN
    SP_MDCH_BEIFUJI_REPORT_DAY(P_TRADEDATE => p_tradeDate,
            P_TABLENAME => NULL,
            P_RETCODE => p_retCode,
            P_RETMSG =>  p_retMsg);
      IF p_retCode != '0' THEN
        p_retCode := 'SBFJ005000';
        p_retMsg  := p_tradeDate || '执行SP_MDCH_BEIFUJI_REPORT_DAY异常';
        ROLLBACK; RETURN;
      END IF;
  END; 
  END IF;

  -- 1 表1
  -- 1.1)插入备付金业务明细表
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT1
    (BFJDATE,BANKCODE)
    SELECT p_tradeDate,SYSTEMCODE
    FROM TD_M_BFJ_BANK
    WHERE ISCOOPERATIVE = '1';
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005002';
      p_retMsg  := '插入备付金业务明细表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT1
    (BFJDATE,BANKCODE)
    VALUES
    (p_tradeDate,'ONEC');
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005002';
      p_retMsg  := '插入备付金业务明细表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --1.2）本期系统反映，本期入金 业务系统中贷记客户资金账户金额
  --当日银行账户和当日系统账务已匹配的转账金额
  BEGIN
    UPDATE TF_F_BFJ_REPORT1 R SET (C1) = (
    SELECT MONEY FROM (
    SELECT SUM(R.MONEY)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION R ON R.BANKTRADEID = B.TRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON R.SYSTEMTRADEID = T.TRADEID
    WHERE B.FILEDATE = p_tradeDate AND T.TRADEDATE = TO_DATE(p_tradeDate,'YYYYMMDD')
	AND B.TRADETYPECODE != '01'
    AND B.AMOUNTTYPE = '0'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION R ON R.BANKTRADEID = B.TRADEID
      INNER JOIN TF_F_BFJ_TRADERECORD T ON R.SYSTEMTRADEID = T.TRADEID
    WHERE B.FILEDATE = p_tradeDate AND T.TRADEDATE = TO_DATE(p_tradeDate,'YYYYMMDD')
	AND B.TRADETYPECODE != '01'
    AND B.AMOUNTTYPE = '0'
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005003';
      p_retMsg  := '更新业务系统中贷记客户资金账户金额失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;



  --1.3）前期系统反映，本期入金 业务系统中贷记客户资金账户金额
  BEGIN
    UPDATE TF_F_BFJ_REPORT1 R SET (C4) = (
    SELECT MONEY FROM (
    SELECT SUM(RR.MONEY)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION RR ON RR.BANKTRADEID = B.TRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON RR.SYSTEMTRADEID = T.TRADEID
    WHERE   T.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd')
    AND FILEDATE =  p_tradeDate 
	AND B.TRADETYPECODE != '01'
	AND B.AMOUNTTYPE = '0'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate, FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION RR ON RR.BANKTRADEID = B.TRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON RR.SYSTEMTRADEID = T.TRADEID
    WHERE  T.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd')
    AND FILEDATE =  p_tradeDate
	AND B.TRADETYPECODE != '01'
    AND B.AMOUNTTYPE = '0'
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005004';
      p_retMsg  := '更新业务系统中贷记客户资金账户金额失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;  
  
  
  --1.4) 更新本期业务系统中已贷记客户资金账户金额
  BEGIN
    UPDATE TF_F_BFJ_REPORT1 R SET (C7) = (
    SELECT MONEY FROM (
		SELECT SUM(TRADEMONEY) / 1000000.0  - SUM(NVL(MONEY,0)) MONEY,NVL(OTHERBANK,'ONEC') OTHERBANK
		FROM TF_F_BFJ_TRADERECORD T
		LEFT JOIN ( SELECT SUM(RR.MONEY)/1000000.0 MONEY,T.TRADEID
				FROM TF_F_BFJ_OCAB B
				INNER JOIN TF_F_BFJ_BANKRELATION RR ON RR.BANKTRADEID = B.TRADEID
				INNER JOIN TF_F_BFJ_TRADERECORD T ON RR.SYSTEMTRADEID = T.TRADEID
				WHERE T.TRADEDATE  = TO_DATE(p_tradeDate,'yyyyMMdd') 
				AND  FILEDATE  <= p_tradeDate
				AND B.TRADETYPECODE != '01'
				AND B.AMOUNTTYPE = '0'
				GROUP BY T.TRADEID) R ON R.TRADEID = T.TRADEID
		WHERE AMOUNTTYPE = '0'
		AND TRADEDATE = TO_DATE(p_tradeDate, 'YYYYMMDD') 
	    AND ISNEEDMATCH = '0'
		AND ISCASH = '0'
		GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,NVL(OTHERBANK,'ONEC') OTHERBANK
    FROM TF_F_BFJ_TRADERECORD T
		LEFT JOIN ( SELECT SUM(RR.MONEY)/1000000.0 MONEY,T.TRADEID
		FROM TF_F_BFJ_OCAB B
		INNER JOIN TF_F_BFJ_BANKRELATION RR ON RR.BANKTRADEID = B.TRADEID
		INNER JOIN TF_F_BFJ_TRADERECORD T ON RR.SYSTEMTRADEID = T.TRADEID
		WHERE T.TRADEDATE  = TO_DATE(p_tradeDate,'yyyyMMdd') 
		AND  FILEDATE  <= p_tradeDate
		AND B.TRADETYPECODE != '01'
		AND B.AMOUNTTYPE = '0'
		GROUP BY T.TRADEID) R ON R.TRADEID = T.TRADEID
		WHERE AMOUNTTYPE = '0'
		AND TRADEDATE = TO_DATE(p_tradeDate, 'YYYYMMDD') 
	    AND ISNEEDMATCH = '0'
		AND ISCASH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005504';
      p_retMsg  := '更新本期业务系统中已贷记客户资金账户金额失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;


  --1.5）支付机构业务系统中未反映但银行已收到的款项 本期收到的金额
  -- 当期未完全匹配的转账银行业务
  BEGIN
    UPDATE TF_F_BFJ_REPORT1 R SET (C10) = (
    SELECT MONEY FROM (
    SELECT (SUM(TRADECHARGE) - SUM(NVL(MONEY,0)))/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '0'
		  AND  TT.TRADETYPECODE != '01' 
          AND  TT.FILEDATE = p_tradeDate
          AND  R.TRADEDATE <= TO_DATE(p_tradeDate,'yyyyMMdd')
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE = p_tradeDate
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND AMOUNTTYPE = '0'
	AND TRADETYPECODE != '01' 
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '0'
		  AND TT.TRADETYPECODE != '01' 
          AND  TT.FILEDATE = p_tradeDate
          AND  R.TRADEDATE <= TO_DATE(p_tradeDate,'yyyyMMdd')
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE = p_tradeDate
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND AMOUNTTYPE = '0'
	AND TRADETYPECODE != '01' 
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005008';
      p_retMsg  := '更新本期业务系统中已贷记客户资金账户金额失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;
  
  --1.6）补入账 
  BEGIN 
    UPDATE TF_F_BFJ_REPORT1 R SET (C11) = (
    SELECT MONEY FROM (
    SELECT SUM(RR.MONEY)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION RR ON RR.BANKTRADEID = B.TRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON RR.SYSTEMTRADEID = T.TRADEID
    WHERE T.TRADEDATE  = TO_DATE(p_tradeDate,'yyyyMMdd') 
    AND  FILEDATE  < p_tradeDate 
	AND B.TRADETYPECODE != '01'
    AND B.AMOUNTTYPE = '0'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION RR ON RR.BANKTRADEID = B.TRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON RR.SYSTEMTRADEID = T.TRADEID
    WHERE T.TRADEDATE  = TO_DATE(p_tradeDate,'yyyyMMdd') 
	AND  FILEDATE  < p_tradeDate 
	AND B.TRADETYPECODE != '01'
    AND B.AMOUNTTYPE = '0'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005005';
      p_retMsg  := '更新补入账金额失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --2 表2
  --2.1)插入备付金出金业务明细表
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT2
    (BFJDATE)
    VALUES
    (p_tradeDate);
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005009';
      p_retMsg  := '插入备付金出金业务明细表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --支付机构业务系统中已反映的出金业务
  --本期业务系统中借记客户资金账户金额 = 本期业务应出金金额 + 本期手续费等收入（支出）

  --2.2）本期业务应出金金额
  --取当期出金业务数据
  --本期手续费等收入（支出）
  BEGIN
    UPDATE TF_F_BFJ_REPORT2 R SET
    C2= (SELECT ABS(SUM(TRADEMONEY))/1000000.0 FROM TF_F_BFJ_TRADERECORD WHERE AMOUNTTYPE = '1' AND TRADEDATE = TO_DATE(p_tradeDate,'YYYYMMDD') AND ISNEEDMATCH = '0')
   ,C3 =(SELECT ABS(SUM(NVL(FEE,0)))/1000000.0 FROM TF_F_BFJ_TRADERECORD WHERE AMOUNTTYPE = '1' AND TRADEDATE = TO_DATE(p_tradeDate,'YYYYMMDD') AND ISNEEDMATCH = '0')
    where BFJDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ001007';
      p_retMsg  := '更新本期手续费等收入（支出）失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;
  
  

    --本期系统反映，本期出金
  --取表3B (明细表)

  --2.3）前期系统反映，本期出金 
  BEGIN
    BEGIN
    SELECT ABS(NVL(SUM(MONEY),0)) into v_money FROM (
	SELECT SUM(MONEY)/1000000.0 MONEY  
    FROM  TF_F_BFJ_OCAB B 
    INNER JOIN TF_F_BFJ_BANKRELATION R ON R.BANKTRADEID = B.TRADEID
    INNER JOIN  TF_F_BFJ_TRADERECORD T ON T.TRADEID = R.SYSTEMTRADEID
    WHERE T.AMOUNTTYPE = '1'   
    AND FILEDATE = p_tradeDate
    AND  T.TRADEDATE < TO_DATE(p_tradeDate,'YYYYMMDD') 
    GROUP BY B.TRADEID
	);
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005010';
      p_retMsg  := '查询前期系统反映，本期出金失败' || SQLERRM;
      ROLLBACK; RETURN;
    END; 
	 BEGIN
    UPDATE TF_F_BFJ_REPORT2 R SET C5 = v_money  where BFJDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005011';
      p_retMsg  := '更新前期系统反映，本期出金失败' || SQLERRM;
      ROLLBACK; RETURN;
    END;
  END; 
  

  --2.4)支付机构业务系统中未反映，但银行已扣款 本期扣款的金额 
  --取当期未完全匹配的银行出金数据  
  BEGIN
    BEGIN
    SELECT ABS(SUM(TRADECHARGE) -  SUM(NVL(MONEY,0)))/1000000.0 MONEY INTO v_money
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '1'
          AND  TT.FILEDATE = p_tradeDate
          AND  R.TRADEDATE <= TO_DATE(p_tradeDate,'yyyyMMdd')
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE = p_tradeDate
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND AMOUNTTYPE = '1'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005012';
      p_retMsg  := '查询本期扣款的金额失败' || SQLERRM;
      ROLLBACK; RETURN;
    END;
    BEGIN
    UPDATE TF_F_BFJ_REPORT2 R SET C6 = v_money where BFJDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005113';
      p_retMsg  := '更新本期扣款的金额失败' || SQLERRM;
      ROLLBACK; RETURN;
    END;
  END;
   
	--2.5）补入账 
  BEGIN 
    UPDATE TF_F_BFJ_REPORT2 R SET C7 = ( 
    SELECT ABS(SUM(RR.MONEY))/1000000.0 MONEY 
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION RR ON RR.BANKTRADEID = B.TRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON RR.SYSTEMTRADEID = T.TRADEID
    WHERE T.TRADEDATE  = TO_DATE(p_tradeDate,'yyyyMMdd') 
    AND  FILEDATE  < p_tradeDate  
    AND B.AMOUNTTYPE = '1' )  
    WHERE  BFJDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005113';
      p_retMsg  := '更新补入账金额失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;
	
  BEGIN
	 UPDATE TF_F_BFJ_REPORT2 R SET C2 = nvl(C2,0) - nvl(C7,0)  WHERE  BFJDATE = p_tradeDate; 
	 EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005113';
      p_retMsg  := '更新补入账金额失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;
   

  --3)备付金业务实际出金明细表
  --3.1) 插入备付金业务实际出金明细表
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT3
    (BFJDATE,BANKCODE,C1,C2,C3)
    SELECT p_tradeDate,SYSTEMCODE,SYSTEMNAME,ACCOUNTNAME,ACCOUNT
    FROM TD_M_BFJ_BANK
    WHERE ISCOOPERATIVE = '1';
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005014';
      p_retMsg  := '插入备付金业务实际出金明细表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;


  --3.2）取本期已匹配的出金信息（银行日期和业务日期都是本期）
  BEGIN
    UPDATE TF_F_BFJ_REPORT3 R SET (C4) = (
    SELECT MONEY FROM (
    SELECT ABS(SUM(R.MONEY))/1000000.0 MONEY,B.BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION R ON B.TRADEID = R.BANKTRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON R.SYSTEMTRADEID = T.TRADEID
    WHERE B.FILEDATE = p_tradeDate
    AND T.TRADEDATE = TO_DATE(p_tradeDate,'YYYYMMDD')
    AND T.AMOUNTTYPE = '1' 
    GROUP BY B.BANKNAME  ) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION R ON B.TRADEID = R.BANKTRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON R.SYSTEMTRADEID = T.TRADEID
    WHERE B.FILEDATE = p_tradeDate
    AND T.TRADEDATE = TO_DATE(p_tradeDate,'YYYYMMDD')
    AND T.AMOUNTTYPE = '1' 
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005015';
      p_retMsg  := '更新金额' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --4.客户资金账户转账业务统计表
  --4.1 插入资金账户转账业务统计表
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT4
    (BFJDATE)
    VALUES
    (p_tradeDate);
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005016';
      p_retMsg  := '插入资金账户转账业务统计表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --4.2 取沉淀资金报表数据
  BEGIN
    BEGIN
    SELECT F1/10000.0,F2/10000.0,F3/10000.0 INTO v_F1,v_F2,v_money  FROM TF_F_BEIFUJINREPORT WHERE tablename = '1-4' AND tradedate = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005017';
      p_retMsg  := '查询金额失败' || SQLERRM;
      ROLLBACK; RETURN;
    END;
    BEGIN
    UPDATE TF_F_BFJ_REPORT4 SET C1 = ABS(v_F1) ,C2 = ABS(v_F2), C3 = ABS(v_money) WHERE BFJDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005018';
      p_retMsg  := '更新金额失败' || SQLERRM;
      ROLLBACK; RETURN;
    END;
  END;


  --5.资金账户转账业务统计表
  --5.1 插入资金账户转账业务统计表
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT5
    (BFJDATE,BANKCODE)
    VALUES
    (p_tradeDate,'ONEC');
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005019';
      p_retMsg  := '插入资金账户转账业务统计表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --5.2 更新记录
  BEGIN
      --客户资金账户借方发生额 客户资金账户贷方发生额 与表4一致
    BEGIN
    UPDATE TF_F_BFJ_REPORT5 SET C4 = ABS(v_F1) ,C5 = ABS(v_F2) WHERE BFJDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005018';
      p_retMsg  := '更新金额失败' || SQLERRM;
      ROLLBACK; RETURN;
    END;


    -- 查询期初数据
    BEGIN
    SELECT C6 INTO v_money FROM TF_F_BFJ_REPORT5 WHERE BFJDATE = TO_CHAR(TO_DATE(p_tradeDate,'yyyyMMdd') -1,'yyyyMMdd');
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
      v_money := 0;
    WHEN OTHERS THEN
      p_retCode := 'SBFJ005020';
      p_retMsg  := '查询期初数据失败' || SQLERRM;
      ROLLBACK; RETURN;
    END;

    --本期入金业务贷记客户资金账户金额 取当期入金业务数据（包括现金备付金）
    --本期出金业务借记客户资金账户金额 取表2 本期业务系统中借记客户资金账户金额
    BEGIN
    UPDATE TF_F_BFJ_REPORT5 SET C1 = v_money ,
    C2 = (SELECT SUM(TRADEMONEY)/1000000.0 FROM TF_F_BFJ_TRADERECORD WHERE AMOUNTTYPE = '0' AND TRADEDATE = TO_DATE(p_tradeDate,'YYYYMMDD') 
	AND ISNEEDMATCH = '0' AND ((ISCASH = '1'   AND TRADETYPECODE   IN ('01','02','03')) OR ISCASH = '0' ) 
	),
    C3 = (SELECT NVL(C2,0)+NVL(C3,0)+NVL(C7,0)  FROM TF_F_BFJ_REPORT2 WHERE BFJDATE = p_tradeDate)
    WHERE BFJDATE = p_tradeDate ;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005022';
      p_retMsg  := '更新记录失败' || SQLERRM;
      ROLLBACK; RETURN;
    END;
	
	 
	
    BEGIN
    UPDATE TF_F_BFJ_REPORT5 SET C6 = C1 + C2 - C3 + C5 - C4 WHERE BFJDATE = p_tradeDate ;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005022';
      p_retMsg  := '更新记录失败' || SQLERRM;
      ROLLBACK; RETURN;
    END;
  END;

  --6.特殊业务明细表
  --6.1 插入备付金业务实际出金明细表
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT6
    (BFJDATE,BANKCODE)
    SELECT p_tradeDate,SYSTEMCODE
    FROM TD_M_BFJ_BANK
    WHERE ISCOOPERATIVE = '1';
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005023';
      p_retMsg  := '插入备付金业务实际出金明细表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT6
    (BFJDATE,BANKCODE)
    VALUES
    (p_tradeDate,'ONEC');
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005002';
      p_retMsg  := '插入备付金业务明细表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.1向备付金银行缴存现金形式备付金
  --取已匹配当期现金备付金
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C2) = (
    SELECT MONEY FROM (
    SELECT SUM(R.MONEY)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION R ON R.BANKTRADEID = B.TRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON R.SYSTEMTRADEID = T.TRADEID
    WHERE B.FILEDATE = p_tradeDate
    AND B.TRADETYPECODE = '01'
    AND T.TRADETYPECODE IN ('01','02','03')  
	--AND T.TRADEDATE <= TO_DATE(p_tradeDate,'YYYYMMDD')
	AND T.TRADEDATE <= TO_DATE(v_lastInMatchdate,'YYYYMMDD')
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION R ON R.BANKTRADEID = B.TRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON R.SYSTEMTRADEID = T.TRADEID
    WHERE B.FILEDATE = p_tradeDate
    AND B.TRADETYPECODE = '01'
    AND T.TRADETYPECODE IN ('01','02','03')  
	--AND T.TRADEDATE <= TO_DATE(p_tradeDate,'YYYYMMDD')
	AND T.TRADEDATE <= TO_DATE(v_lastInMatchdate,'YYYYMMDD')
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005054';
      p_retMsg  := '更新向备付金银行缴存现金形式备付金失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.2更新备付金银行间头寸调拨（调入行）
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C3) = (
    SELECT MONEY FROM (
    SELECT SUM(NVL(TRADECHARGE,0))/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND AMOUNTTYPE = '0'
    AND ((TRADETYPECODE = '03') OR (INSTR(UPPER(TRADEMEG),'DB') > 0 AND ISNEEDMATCH = '1'))
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND AMOUNTTYPE = '0'
    AND ((TRADETYPECODE = '03') OR (INSTR(UPPER(TRADEMEG),'DB') > 0 AND ISNEEDMATCH = '1'))
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005024';
      p_retMsg  := '更新备付金银行间头寸调拨（调入行）失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.2 更新收到利息收入
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C4) = (
    SELECT MONEY FROM (
    SELECT SUM(NVL(TRADECHARGE,0))/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '04'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '04'
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005025';
      p_retMsg  := '更新收到利息收入失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.3 备付金非活期存款转活期存款（活期账户）
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C5) = (
    SELECT MONEY FROM (
    SELECT SUM(NVL(TRADECHARGE,0))/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '05'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '05'
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005026';
      p_retMsg  := '更新备付金非活期存款转活期存款（活期账户）失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.4 更新备付金活期存款转非活期存款（非活期账户）
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C6) = (
    SELECT MONEY FROM (
    SELECT SUM(NVL(TRADECHARGE,0))/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '06'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '06'
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005027';
      p_retMsg  := '更新备付金活期存款转非活期存款（非活期账户）失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.6 当日申请存放的自有资金（存管银行）
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C7) =  (
    SELECT MONEY FROM (
    SELECT SUM(R.MONEY)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION R ON R.BANKTRADEID = B.TRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON R.SYSTEMTRADEID = T.TRADEID
    WHERE FILEDATE = p_tradeDate
    AND B.TRADETYPECODE = '01'
    AND T.TRADETYPECODE IN ('10','12','14')
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate, FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION R ON R.BANKTRADEID = B.TRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON R.SYSTEMTRADEID = T.TRADEID
    WHERE  FILEDATE = p_tradeDate
    AND B.TRADETYPECODE = '01'
    AND T.TRADETYPECODE IN ('10','12','14')
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005004';
      p_retMsg  := '更新当日申请存放的自有资金失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.5 更新利息收入划拨存管银行
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C8) = (
    SELECT MONEY FROM (
    SELECT SUM(NVL(TRADECHARGE,0))/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '07'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '07'
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005028';
      p_retMsg  := '更新更新利息收入划拨存管银行失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.5 向备付金银行缴存现金形式预付卡押金
  -- 当期现金押金
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C10) = (
    SELECT MONEY FROM (
    SELECT SUM(TRADEMONEY)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION R ON R.BANKTRADEID = B.TRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON R.SYSTEMTRADEID = T.TRADEID
    WHERE FILEDATE  =  p_tradeDate
    AND B.TRADETYPECODE = '01'
    AND T.TRADETYPECODE = '15'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    INNER JOIN TF_F_BFJ_BANKRELATION R ON R.BANKTRADEID = B.TRADEID
    INNER JOIN TF_F_BFJ_TRADERECORD T ON R.SYSTEMTRADEID = T.TRADEID
    WHERE  FILEDATE  =  p_tradeDate
    AND B.TRADETYPECODE = '01'
    AND T.TRADETYPECODE = '15'
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005070';
      p_retMsg  := '更新向备付金银行缴存现金形式预付卡押金失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --其他入金
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C11) = 
    (
	SELECT (SELECT NVL(SUM(TRADECHARGE),0)/1000000.0  FROM TF_F_BFJ_OCAB B WHERE B.FILEDATE  =  p_tradeDate AND B.BANKNAME = R.BANKCODE AND AMOUNTTYPE = '0')
    -
    (SELECT SUM(NVL(C1,0)) + SUM(NVL(C4,0))  + SUM(NVL(C10,0))  FROM TF_F_BFJ_REPORT1 T1 WHERE T1.BFJDATE  =  p_tradeDate AND T1.BANKCODE = R.BANKCODE)
     -
    (SELECT SUM(NVL(C2,0)) + SUM(NVL(C3,0)) + SUM(NVL(C4,0)) + SUM(NVL(C5,0)) + SUM(NVL(C6,0)) +
    SUM(NVL(C7,0)) + SUM(NVL(C8,0)) + SUM(NVL(C10,0))    FROM TF_F_BFJ_REPORT6 T6 WHERE T6.BFJDATE  =  p_tradeDate AND T6.BANKCODE = R.BANKCODE)
    FROM  DUAL )
	WHERE R.BFJDATE = p_tradeDate ;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005070';
      p_retMsg  := '更新其他入金失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;



  --6.6 更新更新备付金银行间头寸调拨（调出行）
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C14) = (
    SELECT MONEY FROM (
    SELECT SUM(NVL(TRADECHARGE,0))/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND AMOUNTTYPE = '1'
    AND ((TRADETYPECODE = '09') OR (INSTR(UPPER(TRADEMEG),'DB') > 0 AND ISNEEDMATCH = '1'))
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND AMOUNTTYPE = '1'
    AND ((TRADETYPECODE = '09') OR (INSTR(UPPER(TRADEMEG),'DB') > 0 AND ISNEEDMATCH = '1'))
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005029';
      p_retMsg  := '更新更新更新备付金银行间头寸调拨（调出行）失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;


  --6.7 更新利息收入划拨存管银行
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C15) = (
    SELECT MONEY FROM (
    SELECT SUM(TRADECHARGE)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '11'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '11'
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005030';
      p_retMsg  := '更新利息收入划拨存管银行失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.8 更新银行扣取手续费、管理费等费用
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C16) = (
    SELECT MONEY FROM (
    SELECT SUM(TRADECHARGE)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '12'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '12'
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005031';
      p_retMsg  := '更新更新银行扣取手续费、管理费等费用失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.9 更新备付金非活期存款转活期存款（非活期账户）
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C17) =  (
    SELECT MONEY FROM (
    SELECT SUM(TRADECHARGE)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '13'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '13'
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005032';
      p_retMsg  := '更新更新备付金非活期存款转活期存款（非活期账户）失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.10 更新备付金活期存款转非活期存款（活期账户）
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C18)  =  (
    SELECT MONEY FROM (
    SELECT SUM(TRADECHARGE)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '14'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate AND TRADETYPECODE = '14'
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005033';
      p_retMsg  := '更新更新备付金活期存款转非活期存款（活期账户）失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.11 更新结转风险准备金（存管银行）
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C19) = (
    SELECT MONEY FROM (
    SELECT SUM(TRADECHARGE)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND AMOUNTTYPE = '1'
    AND ((TRADETYPECODE = '15') OR (INSTR(UPPER(TRADEMEG),'FX') > 0 AND ISNEEDMATCH = '1'))
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND AMOUNTTYPE = '1'
    AND ((TRADETYPECODE = '15') OR (INSTR(UPPER(TRADEMEG),'FX') > 0 AND ISNEEDMATCH = '1'))
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005034';
      p_retMsg  := '更新更新结转风险准备金（存管银行）失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.12 更新结转利息收入（存管银行）
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C20) = (
    SELECT MONEY FROM (
    SELECT SUM(TRADECHARGE)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND TRADETYPECODE IN ('10','16') AND ISNEEDMATCH = '1' AND INSTR(UPPER(TRADEMEG),'LXSR') > 0
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND TRADETYPECODE IN ('10','16') AND ISNEEDMATCH = '1' AND INSTR(UPPER(TRADEMEG),'LXSR') > 0
    AND TRADEMEG LIKE '%结转利息收入%'
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005034';
      p_retMsg  := '更新结转利息收入（存管银行）失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.12 结转手续费收入（存管银行）
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C21) = (
    SELECT MONEY FROM (
    SELECT SUM(TRADECHARGE)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND TRADETYPECODE IN ('10','16') AND ISNEEDMATCH = '1' AND INSTR(UPPER(TRADEMEG),'SXF') > 0
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND TRADETYPECODE IN ('10','16') AND ISNEEDMATCH = '1' AND INSTR(UPPER(TRADEMEG),'SXF') > 0
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005034';
      p_retMsg  := '更新结转手续费收入失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.13 办理预付卡先行现金赎回业务
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C22) = (
    SELECT MONEY FROM (
    SELECT SUM(TRADECHARGE)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND TRADETYPECODE IN ('10','16') AND INSTR(UPPER(TRADEMEG),'SH') > 0
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND TRADETYPECODE IN ('10','16') AND INSTR(UPPER(TRADEMEG),'SH') > 0
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005034';
      p_retMsg  := '更新办理预付卡先行现金赎回业务失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.12 当日提出原申请存放的自有资金
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C23) = (
    SELECT MONEY FROM (
    SELECT SUM(TRADECHARGE)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND TRADETYPECODE IN ('10','16') AND INSTR(UPPER(TRADEMEG),'ZY') > 0
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND TRADETYPECODE IN ('10','16') AND INSTR(UPPER(TRADEMEG),'ZY') > 0
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005034';
      p_retMsg  := '更新当日提出原申请存放的自有资金失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.12 更新以转账方式退回购卡押金
  --取当期银行数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C25) = (
    SELECT MONEY FROM (
    SELECT SUM(TRADECHARGE)/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND TRADETYPECODE IN ('10','16') AND INSTR(UPPER(TRADEMEG),'YJ') > 0
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB B
    WHERE FILEDATE = p_tradeDate
    AND TRADETYPECODE IN ('10','16') AND INSTR(UPPER(TRADEMEG),'YJ') > 0
    GROUP BY FILEDATE,BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005034';
      p_retMsg  := '更新以转账方式退回购卡押金失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --6.13办理预付卡押金先行现金赎回业务（存管银行）
    --暂无

    --其他出金
  BEGIN
    UPDATE TF_F_BFJ_REPORT6 R SET (C27) = 
    (
	SELECT (SELECT NVL(SUM(TRADECHARGE),0)/1000000.0  FROM TF_F_BFJ_OCAB B WHERE B.FILEDATE  =  p_tradeDate AND B.BANKNAME = R.BANKCODE AND B.AMOUNTTYPE = '1')
    - 
    (SELECT NVL(SUM(TRADECHARGE),0)/1000000.0  FROM TF_F_BFJ_OCAB B1 
	WHERE B1.FILEDATE  =  p_tradeDate AND B1.BANKNAME = R.BANKCODE AND B1.AMOUNTTYPE = '1' AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0'))
     -
    (SELECT SUM(NVL(C14,0)) + SUM(NVL(C15,0)) + SUM(NVL(C16,0)) + SUM(NVL(C17,0)) + SUM(NVL(C18,0)) + SUM(NVL(C19,0)) +
    SUM(NVL(C20,0)) + SUM(NVL(C21,0)) + SUM(NVL(C22,0)) + SUM(NVL(C23,0)) + SUM(NVL(C25,0))+ SUM(NVL(C26,0))
	FROM TF_F_BFJ_REPORT6 T6 WHERE T6.BFJDATE  =  p_tradeDate AND T6.BANKCODE = R.BANKCODE)
    FROM  DUAL )
	WHERE R.BFJDATE = p_tradeDate ;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005070';
      p_retMsg  := '更新其他出金失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --7 现金购卡业务统计表
  --7.1 插入资金账户转账业务统计表
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT7
    (BFJDATE)
    VALUES
    (p_tradeDate);
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005035';
      p_retMsg  := '插入资金账户转账业务统计表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --7.2 查询客户资金账户期初余额
  BEGIN
    SELECT C4 INTO v_money  FROM TF_F_BFJ_REPORT7 WHERE BFJDATE = TO_CHAR(TO_DATE(p_tradeDate,'yyyyMMdd') -1,'yyyyMMdd');
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
      v_money := 0;
    WHEN OTHERS THEN
      p_retCode := 'SBFJ005036';
      p_retMsg  := '查询客户资金账户期初余额失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --7.5 本期接受现金形式的客户备付金金额
  --取本期业务现金入金数据
  --本期向备付金银行缴存的现金备付金
  --取本期已匹配的银行解款备付金
  BEGIN
    UPDATE TF_F_BFJ_REPORT7 SET C1 = v_money ,
    C2 = (SELECT SUM(TRADEMONEY)/1000000.0 FROM TF_F_BFJ_TRADERECORD
                        WHERE TRADEDATE = TO_DATE(p_tradeDate,'YYYYMMDD')
                          AND AMOUNTTYPE = '0'  AND TRADETYPECODE IN ('01','02','03')   
                        AND ISNEEDMATCH = '0' AND ISCASH = '1'),
    C3 = (SELECT SUM(R.MONEY)/1000000.0
        FROM TF_F_BFJ_OCAB O
        INNER JOIN TF_F_BFJ_BANKRELATION R ON O.TRADEID = R.BANKTRADEID
        INNER JOIN TF_F_BFJ_TRADERECORD T ON T.TRADEID = R.SYSTEMTRADEID
        WHERE O.FILEDATE = p_tradeDate 
        AND O.TRADETYPECODE = '01'
		AND T.TRADETYPECODE IN ('01','02','03')   
		--AND T.TRADEDATE <= TO_DATE(p_tradeDate,'YYYYMMDD')
		AND TRADEDATE <= TO_DATE(v_lastInMatchdate,'YYYYMMDD')
		)
    WHERE BFJDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005039';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --8. 预付卡现金赎回业务统计表
  --8.1 插入资金账户转账业务统计表
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT8
    (BFJDATE)
    VALUES
    (p_tradeDate);
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005040';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --8.2 查询期初以自有资金先行赎回预付卡的余额
  BEGIN
    SELECT C4 INTO v_money FROM TF_F_BFJ_REPORT8 WHERE BFJDATE = TO_CHAR(TO_DATE(p_tradeDate,'yyyyMMdd') -1,'yyyyMMdd');
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
      v_money := 0;
    WHEN OTHERS THEN
      p_retCode := 'SBFJ005041';
      p_retMsg  := '查询期初以自有资金先行赎回预付卡的余额失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --8.3 查询本期以自有资金先行赎回预付卡的金额
  BEGIN
    SELECT ABS(SUM(C22)) INTO v_F2
    FROM TF_F_BFJ_REPORT6
    WHERE BFJDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005042';
      p_retMsg  := '查询本期向备付金存管银行申请结转的金额失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --8.4 本期本期向备付金存管银行申请结转的金额
  BEGIN
    SELECT F1/10000.0  INTO v_F1
    FROM TF_F_BEIFUJINREPORT
    WHERE TABLENAME = '1-8' AND TRADEDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005042';
      p_retMsg  := '查询本期以自有资金先行赎回预付卡的金额失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --8.5 更新数据
  BEGIN
    UPDATE TF_F_BFJ_REPORT8 SET C1 = v_money ,C2 = ABS(v_F1), C3 = ABS(v_F1)  WHERE BFJDATE = p_tradeDate ;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005043';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --9 备付金业务未达账项统计表
  --9.1 插入备付金业务实际出金明细表
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT9
    (BFJDATE,BANKCODE)
    SELECT p_tradeDate,SYSTEMCODE
    FROM TD_M_BFJ_BANK
    WHERE ISCOOPERATIVE = '1';
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005044';
      p_retMsg  := '插入备付金业务实际出金明细表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT9
    (BFJDATE,BANKCODE)
    VALUES
    (p_tradeDate,'ONEC');
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005044';
      p_retMsg  := '插入备付金业务实际出金明细表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;


  --9.2 支付机构业务系统已增加客户资金账户余额，备付金银行未增加备付金银行账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT9 R SET (C1) = (
    SELECT MONEY FROM (
    SELECT (ABS(SUM(TRADEMONEY)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,NVL(OTHERBANK,'ONEC') OTHERBANK
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '0' AND TT.ISNEEDMATCH = '0' 
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
           AND O.FILEDATE <= p_tradeDate
		   AND TT.ISCASH = '0'
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND AMOUNTTYPE = '0' AND ISNEEDMATCH = '0'
	AND ISCASH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,NVL(OTHERBANK,'ONEC') OTHERBANK
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '0' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
           AND O.FILEDATE <= p_tradeDate
		   AND TT.ISCASH = '0'
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND AMOUNTTYPE = '0' AND ISNEEDMATCH = '0'
	AND ISCASH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005045';
      p_retMsg  := '更新银行未达账失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --9.3 支付机构业务系统已减少客户资金账户余额，备付金银行未减少备付金银行账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT9 R SET (C2) = (
    SELECT MONEY FROM (
    SELECT (ABS(SUM(TRADEMONEY)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,NVL(OTHERBANK,'ONEC') OTHERBANK
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '1' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND AMOUNTTYPE = '1' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,NVL(OTHERBANK,'ONEC') OTHERBANK
    FROM TF_F_BFJ_TRADERECORD  T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '1' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND AMOUNTTYPE = '1' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005046';
      p_retMsg  := '更新银行未达账失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --9.4 备付金银行已增加备付金银行账户余额，支付机构业务系统未增加客户资金账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT9 R SET (C3) = (
    SELECT MONEY FROM (
    SELECT (ABS(SUM(TRADECHARGE)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '0'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
		  AND TT.TRADETYPECODE != '01'
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	AND TRADETYPECODE != '01'
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND AMOUNTTYPE = '0'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT BANKNAME
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '0'
		  AND TT.TRADETYPECODE != '01'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	AND TRADETYPECODE != '01'
    --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND AMOUNTTYPE = '0'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND p_tradeDate = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005047';
      p_retMsg  := '更新业务未达账入金失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --9.5 备付金银行已减少备付金银行账户余额，支付机构业务系统未减少客户资金账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT9 R SET (C4) = (
    SELECT MONEY FROM (
    SELECT (ABS(SUM(TRADECHARGE)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,BANKNAME
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '1'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND AMOUNTTYPE = '1'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT BANKNAME
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '1'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND AMOUNTTYPE = '1'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND p_tradeDate = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005048';
      p_retMsg  := '更新业务未达账出金失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --10. 客户备付金业务未达账项分析表
  --10.1 插入备付金业务实际出金明细表
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT10
    (BFJDATE,BANKCODE)
    SELECT p_tradeDate,SYSTEMCODE
    FROM TD_M_BFJ_BANK
    WHERE ISCOOPERATIVE = '1';
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005049';
      p_retMsg  := '插入备付金业务实际出金明细表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT10
    (BFJDATE,BANKCODE)
    VALUES
    (p_tradeDate,'ONEC');
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005049';
      p_retMsg  := '插入备付金业务实际出金明细表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新数据 支付机构业务系统已减少客户资金账户余额，备付金银行未减少备付金银行账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT10 R SET (C1,C2) = (
    SELECT COUNTT,MONEY FROM (
    SELECT (ABS(SUM(TRADEMONEY)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,NVL(OTHERBANK,'ONEC') OTHERBANK,COUNT(TRADEID) COUNTT
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '0' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		   AND TT.ISCASH = '0'
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
	AND ISCASH = '0'
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) <= 5
    AND AMOUNTTYPE = '0' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT p_tradeDate FILEDATE,NVL(OTHERBANK,'ONEC') OTHERBANK
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '0' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		   AND TT.ISCASH = '0'
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
	AND ISCASH = '0'
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) <= 5
    AND AMOUNTTYPE = '0' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005050';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新数据 支付机构业务系统已减少客户资金账户余额，备付金银行未减少备付金银行账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT10 R SET (C3,C4) = (
    SELECT COUNTT,MONEY FROM (
    SELECT  (ABS(SUM(TRADEMONEY)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,NVL(OTHERBANK,'ONEC') OTHERBANK,COUNT(TRADEID) COUNTT
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '0' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		   AND TT.ISCASH = '0'
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
	AND ISCASH = '0'
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) >= 6
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) <= 10
    AND AMOUNTTYPE = '0' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,NVL(OTHERBANK,'ONEC') OTHERBANK
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '0' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		   AND TT.ISCASH = '0'
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
	AND ISCASH = '0'
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) >= 6
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) <= 10
    AND AMOUNTTYPE = '0' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005051';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新数据 支付机构业务系统已减少客户资金账户余额，备付金银行未减少备付金银行账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT10 R SET (C5,C6) = (
    SELECT COUNTT,MONEY FROM (
    SELECT (ABS(SUM(TRADEMONEY)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,NVL(OTHERBANK,'ONEC') OTHERBANK,COUNT(TRADEID) COUNTT
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '0' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		   AND TT.ISCASH = '0'
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
	AND ISCASH = '0'
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) >= 11
    AND AMOUNTTYPE = '0' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,NVL(OTHERBANK,'ONEC') OTHERBANK
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '0' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		   AND TT.ISCASH = '0'
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
	AND ISCASH = '0'
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) >= 11
    AND AMOUNTTYPE = '0' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005052';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新数据 支付机构业务系统已减少客户资金账户余额，备付金银行未减少备付金银行账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT10 R SET (C7,C8) = (
    SELECT COUNTT,MONEY FROM (
    SELECT (ABS(SUM(TRADEMONEY)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,NVL(OTHERBANK,'ONEC') OTHERBANK,COUNT(TRADEID) COUNTT
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '1' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		   
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
	
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) <= 5
    AND AMOUNTTYPE = '1' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,NVL(OTHERBANK,'ONEC') OTHERBANK
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '1' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		   
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
	
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) <= 5
    AND AMOUNTTYPE = '1' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005053';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新数据 支付机构业务系统已减少客户资金账户余额，备付金银行未减少备付金银行账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT10 R SET (C9,C10) = (
    SELECT COUNTT,MONEY FROM (
    SELECT (ABS(SUM(TRADEMONEY)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,NVL(OTHERBANK,'ONEC') OTHERBANK,COUNT(TRADEID) COUNTT
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '1' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		   
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
	
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) >= 6
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) <= 10
    AND AMOUNTTYPE = '1' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,NVL(OTHERBANK,'ONEC') OTHERBANK
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '1' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		   
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
	
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) >= 6
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) <= 10
    AND AMOUNTTYPE = '1' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005054';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新数据 支付机构业务系统已减少客户资金账户余额，备付金银行未减少备付金银行账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT10 R SET (C11,C12) = (
    SELECT COUNTT,MONEY FROM (
    SELECT (ABS(SUM(TRADEMONEY)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,NVL(OTHERBANK,'ONEC') OTHERBANK,COUNT(TRADEID) COUNTT
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '1' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		   
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
	
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) >= 11
    AND AMOUNTTYPE = '1' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,NVL(OTHERBANK,'ONEC') OTHERBANK
    FROM TF_F_BFJ_TRADERECORD T
    LEFT JOIN (SELECT TT.TRADEID SYSTEMTRADEID, SUM(MONEY) MONEY
           FROM TF_F_BFJ_TRADERECORD TT
           INNER JOIN TF_F_BFJ_BANKRELATION B ON B.SYSTEMTRADEID = TT.TRADEID
           INNER JOIN TF_F_BFJ_OCAB O ON B.BANKTRADEID = O.TRADEID
           WHERE TT.AMOUNTTYPE = '1' AND TT.ISNEEDMATCH = '0'
           AND TT.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		   
           AND O.FILEDATE <= p_tradeDate
           GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.SYSTEMTRADEID
    WHERE TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
	
    AND (R.SYSTEMTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADEMONEY))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TRADEDATE) >= 11
    AND AMOUNTTYPE = '1' AND ISNEEDMATCH = '0'
    GROUP BY NVL(OTHERBANK,'ONEC')) T2 WHERE T2.OTHERBANK = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005055';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新数据 备付金银行已增加备付金银行账户余额，支付机构业务系统未增加客户资金账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT10 R SET (C13,C14) = (
    SELECT COUNTT,MONEY FROM (
    SELECT (ABS(SUM(TRADECHARGE)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,BANKNAME,COUNT(TRADEID) COUNTT
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '0'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
		  AND TT.TRADETYPECODE != '01'
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) <= 5
    AND AMOUNTTYPE = '0'
	AND TRADETYPECODE != '01'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '0'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
		  AND TT.TRADETYPECODE != '01'
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) <= 5 AND AMOUNTTYPE = '0'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
	AND TRADETYPECODE != '01'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005056';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新数据 备付金银行已增加备付金银行账户余额，支付机构业务系统未增加客户资金账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT10 R SET (C15,C16) = (
    SELECT COUNTT,MONEY FROM (
    SELECT (ABS(SUM(TRADECHARGE)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,BANKNAME,COUNT(TRADEID) COUNTT
    FROM TF_F_BFJ_OCAB   T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '0'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		  AND TT.TRADETYPECODE != '01'
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) >= 6
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) <= 10
    AND AMOUNTTYPE = '0'
	AND TRADETYPECODE != '01'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '0'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
		  AND TT.TRADETYPECODE != '01'
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) <= 5 AND AMOUNTTYPE = '0'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
	AND TRADETYPECODE != '01'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005057';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新数据 备付金银行已增加备付金银行账户余额，支付机构业务系统未增加客户资金账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT10 R SET (C17,C18) = (
    SELECT COUNTT,MONEY FROM (
    SELECT (ABS(SUM(TRADECHARGE)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,BANKNAME,COUNT(TRADEID) COUNTT
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '0'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
		  AND TT.TRADETYPECODE != '01'
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) >= 11 AND AMOUNTTYPE = '0'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
	AND TRADETYPECODE != '01'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT  p_tradeDate FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '0'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
		  AND TT.TRADETYPECODE != '01'
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) >= 11 AND AMOUNTTYPE = '0'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
	AND TRADETYPECODE != '01'
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005058';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新数据 备付金银行已减少备付金银行账户余额，支付机构业务系统未减少客户资金账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT10 R SET (C19,C20) = (
    SELECT COUNTT,MONEY FROM (
    SELECT (ABS(SUM(TRADECHARGE)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,BANKNAME,COUNT(TRADEID) COUNTT
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '1'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) <=5 AND AMOUNTTYPE = '1'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT p_tradeDate FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '1'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) <=5 AND AMOUNTTYPE = '1'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005059';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新数据 备付金银行已减少备付金银行账户余额，支付机构业务系统未减少客户资金账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT10 R SET (C21,C22) = (
    SELECT COUNTT,MONEY FROM (
    SELECT (ABS(SUM(TRADECHARGE)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,BANKNAME,COUNT(TRADEID) COUNTT
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '1'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) >= 6
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) <= 10
    AND AMOUNTTYPE = '1'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT p_tradeDate FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '1'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) >= 6
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) <= 10
    AND AMOUNTTYPE = '1'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005060';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新数据 备付金银行已减少备付金银行账户余额，支付机构业务系统未减少客户资金账户余额
  BEGIN
    UPDATE TF_F_BFJ_REPORT10 R SET (C23,C24) = (
    SELECT COUNTT,MONEY FROM (
    SELECT (ABS(SUM(TRADECHARGE)) - ABS(SUM(NVL(MONEY,0))))/1000000.0 MONEY,BANKNAME,COUNT(TRADEID) COUNTT
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '1'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd')) >= 11 AND AMOUNTTYPE = '1'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE
    )
    WHERE R.BFJDATE = p_tradeDate AND exists (select 1 from
    (
    SELECT p_tradeDate FILEDATE,BANKNAME
    FROM TF_F_BFJ_OCAB T
    LEFT JOIN (SELECT TT.TRADEID BANKTRADEID,SUM(MONEY) MONEY
          FROM TF_F_BFJ_OCAB TT
          INNER JOIN TF_F_BFJ_BANKRELATION B ON B.BANKTRADEID = TT.TRADEID
          INNER JOIN TF_F_BFJ_TRADERECORD R ON R.TRADEID = B.SYSTEMTRADEID
          WHERE TT.AMOUNTTYPE = '1'
          AND  TT.FILEDATE <= p_tradeDate
		  --AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
          AND  R.TRADEDATE < TO_DATE(p_tradeDate,'yyyyMMdd') + 1
          AND (TT.ISNEEDMATCH IS NULL OR TT.ISNEEDMATCH = '0')
          GROUP BY TT.TRADEID) R
    ON T.TRADEID = R.BANKTRADEID
    WHERE FILEDATE <= p_tradeDate
	--AND  FILEDATE >= TO_CHAR(TRUNC(TO_DATE(p_tradeDate,'yyyyMMdd'), 'mm'),'YYYYMMDD')
    AND (R.BANKTRADEID IS NULL OR ABS(R.MONEY) != ABS(T.TRADECHARGE))
    AND trunc(TO_DATE(p_tradeDate,'yyyyMMdd'))-trunc(TO_DATE(FILEDATE,'yyyyMMdd'))  >= 11 AND AMOUNTTYPE = '1'
    AND (ISNEEDMATCH IS NULL OR ISNEEDMATCH = '0' )
    GROUP BY BANKNAME) T2 WHERE T2.BANKNAME = r.BANKCODE AND T2.FILEDATE = R.BFJDATE
    );
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005061';
      p_retMsg  := '更新数据失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --13. 备付金账户中售卡押金统计表
  --13.1 插入售卡押金统计表表
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT13
    (BFJDATE,C1,C2,C3,C4,C5,C6)
    SELECT   p_tradeDate,f1/10000.0,f2/10000.0,0,0,f5/10000.0,f6/10000.0
    FROM  TF_F_beifujinreport WHERE tablename = '1-13' AND tradedate = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005062';
      p_retMsg  := '插入售卡押金统计表表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  BEGIN
    UPDATE TF_F_BFJ_REPORT13 SET C3 = (SELECT SUM(NVL(C10,0)) FROM TF_F_BFJ_REPORT6 WHERE BFJDATE = p_tradeDate),
    C4 = (SELECT SUM(NVL(C25,0)) FROM TF_F_BFJ_REPORT6 WHERE BFJDATE = p_tradeDate),
    C5 = (SELECT SUM(NVL(C26,0)) FROM TF_F_BFJ_REPORT6 WHERE BFJDATE = p_tradeDate)
    WHERE BFJDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005062';
      p_retMsg  := '更新售卡押金统计表表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --14 银行账户余额统计表
  BEGIN
    INSERT INTO TF_F_BFJ_REPORT2_1
    (BFJDATE)
    values
    (p_tradeDate);
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005063';
      p_retMsg  := '插入银行账户余额统计表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  BEGIN
    UPDATE TF_F_BFJ_REPORT2_1
    SET (C1,C2,C4,C5,C7,C8,C10,C11,C13,C14,C16,C17,C18,C19,C21,C22,
    C24,C25,C27,C28,C30,C31,C33,C34,C36,C37)
    =
    (
    SELECT SZ1,SZ2,NY1,NY2,ZG1,ZG2,GS1,GS2,JT1,JT2,CB1,CB2,GD1,GD2,GS3,GS4,JS1,JS2,
    '南京银行',5000,'中国银行',8000,NVL(SZ3,'苏州银行'),NVL(SZ4,40000.0),NY3,NY4
    FROM
    (SELECT BANKACCOUNT SZ1,BFJBALANCE/1000000.0 SZ2,FILEDATE FROM TF_F_BFJ_OBAB 
		WHERE FILEDATE = p_tradeDate AND BANKCODE = 'SZYH'
		AND BANKACCOUNT = '7066602001120105002221' ) T1
    INNER JOIN (SELECT BANKACCOUNT NY1,BFJBALANCE /1000000.0  NY2,FILEDATE FROM TF_F_BFJ_OBAB O
          INNER JOIN TD_M_BFJ_BANK B ON O.BANKCODE= B.SYSTEMCODE AND B.ACCOUNT = O.BANKACCOUNT
          WHERE FILEDATE = p_tradeDate AND O.BANKCODE = 'NYYH') T2 ON T1.FILEDATE = T2.FILEDATE
    INNER JOIN (SELECT BANKACCOUNT ZG1,BFJBALANCE /1000000.0  ZG2,FILEDATE FROM TF_F_BFJ_OBAB O
          INNER JOIN TD_M_BFJ_BANK B ON O.BANKCODE= B.SYSTEMCODE AND B.ACCOUNT = O.BANKACCOUNT
          WHERE FILEDATE = p_tradeDate AND O.BANKCODE = 'ZGYH' ) T3 ON T3.FILEDATE = T2.FILEDATE
    INNER JOIN (SELECT BANKACCOUNT GS1,BFJBALANCE /1000000.0  GS2,FILEDATE FROM TF_F_BFJ_OBAB O
          INNER JOIN TD_M_BFJ_BANK B ON O.BANKCODE= B.SYSTEMCODE AND B.ACCOUNT = O.BANKACCOUNT
          WHERE FILEDATE = p_tradeDate AND O.BANKCODE = 'GSYH') T4 ON T4.FILEDATE = T3.FILEDATE
    INNER JOIN (SELECT BANKACCOUNT JT1,BFJBALANCE /1000000.0  JT2,FILEDATE FROM TF_F_BFJ_OBAB O
          INNER JOIN TD_M_BFJ_BANK B ON O.BANKCODE= B.SYSTEMCODE AND B.ACCOUNT = O.BANKACCOUNT
          WHERE FILEDATE = p_tradeDate AND O.BANKCODE = 'JTYH') T5 ON T5.FILEDATE = T4.FILEDATE
    INNER JOIN (SELECT BANKACCOUNT CB1,BFJBALANCE /1000000.0  CB2,FILEDATE FROM TF_F_BFJ_OBAB O
          INNER JOIN TD_M_BFJ_BANK B ON O.BANKCODE= B.SYSTEMCODE AND B.ACCOUNT = O.BANKACCOUNT
          WHERE FILEDATE = p_tradeDate AND O.BANKCODE = 'CBYH') T6 ON T6.FILEDATE = T5.FILEDATE
    INNER JOIN (SELECT BANKACCOUNT GD1,BFJBALANCE /1000000.0  GD2,FILEDATE FROM TF_F_BFJ_OBAB O
          INNER JOIN TD_M_BFJ_BANK B ON O.BANKCODE= B.SYSTEMCODE AND B.ACCOUNT = O.BANKACCOUNT
          WHERE FILEDATE = p_tradeDate AND O.BANKCODE = 'GDYH') T7 ON T7.FILEDATE = T6.FILEDATE 
    LEFT JOIN (SELECT BANKACCOUNT JS1,BFJBALANCE /1000000.0  JS2,FILEDATE FROM TF_F_BFJ_OBAB O
           WHERE FILEDATE = p_tradeDate AND O.BANKCODE = 'JSYH' ) T9 ON T9.FILEDATE = T1.FILEDATE
	LEFT JOIN (SELECT '工商银行' GS3,SUM(BFJBALANCE) /1000000.0  GS4,p_tradeDate FILEDATE FROM TF_F_BFJ_OBAB O
           WHERE FILEDATE = p_tradeDate AND O.BANKCODE = 'GSYH'  AND O.BANKACCOUNT != '1102020629000840880'
		   GROUP BY FILEDATE) T8 ON T8.FILEDATE = T7.FILEDATE 
    LEFT JOIN  (SELECT '农业银行' NY3,SUM(BFJBALANCE) /1000000.0  NY4,FILEDATE FROM TF_F_BFJ_OBAB O
           WHERE FILEDATE = p_tradeDate AND O.BANKCODE = 'NYYH' AND O.BANKACCOUNT != '553301040004064' 
          GROUP BY FILEDATE) T10 ON T10.FILEDATE = T1.FILEDATE
	LEFT JOIN  (SELECT '苏州银行' SZ3,SUM(BFJBALANCE) /1000000.0  SZ4,FILEDATE FROM TF_F_BFJ_OBAB O
           WHERE FILEDATE = p_tradeDate AND O.BANKCODE = 'SZYH' AND O.BANKACCOUNT != '7066602001120105002221'	 
		   GROUP BY FILEDATE) T11 ON T11.FILEDATE = T1.FILEDATE
    )
    WHERE BFJDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005064';
      p_retMsg  := '更新银行账户余额统计表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;

  --更新任务表
  BEGIN
    UPDATE TF_F_BFJ_TASK SET ISREPORT = '1' , REPORTDATE = v_now WHERE BFJDATE = p_tradeDate;
    EXCEPTION WHEN OTHERS THEN
      p_retCode := 'SBFJ005065';
      p_retMsg  := '更新任务表失败' || SQLERRM;
      ROLLBACK; RETURN;
  END;


  p_retCode := '0000000000';
    p_retMsg  := 'OK';
    COMMIT;
    RETURN;
end;

/
show errors;