/* ------------------------------------
COPYRIGHT (C) 2010-2015 LINKAGE SOFTWARE 
 ALL RIGHTS RESERVED.
<AUTHOR>JIANGBB</AUTHOR>
<CREATEDATE>2014-08-08</CREATEDATE>
<DESCRIPTION>业务删除存储过程</DESCRIPTION>
------------------------------------ */
CREATE OR REPLACE PROCEDURE SP_PN_FinanceDel
(
	P_SESSIONID			VARCHAR2,	--SESSIONID
	
	P_CURROPER          CHAR,
    P_CURRDEPT          CHAR,
    P_RETCODE   		OUT CHAR, -- RETURN CODE
    P_RETMSG    		OUT VARCHAR2  -- RETURN MESSAGE
)
AS
	V_EX				EXCEPTION;
BEGIN

	FOR V_C IN (SELECT F1,F2 FROM TMP_COMMON WHERE F0 = P_SESSIONID) LOOP
		--银行数据
		IF V_C.F1 = '0' THEN
			BEGIN
			UPDATE TF_F_BFJ_OCAB T 
			SET T.ISNEEDMATCH = '1'
			WHERE T.TRADEID = V_C.F2;
			EXCEPTION
				WHEN OTHERS THEN
					P_RETCODE := 'S05001C001'; P_RETMSG  := '更新银行备付金交易明细表失败,' || SQLERRM;
					ROLLBACK; RETURN;
			END;
		--业务数据
		ELSIF V_C.F1 = '1' THEN
			BEGIN
			UPDATE TF_F_BFJ_TRADERECORD T 
			SET T.ISNEEDMATCH = '1'
			WHERE T.TRADEID = V_C.F2;
			EXCEPTION
				WHEN OTHERS THEN
					P_RETCODE := 'S05001C002'; P_RETMSG  := '更新系统业务账单表失败,' || SQLERRM;
					ROLLBACK; RETURN;
			END;
		END IF;
	END LOOP;

	
	

    P_RETCODE := '0000000000'; P_RETMSG := '';
    COMMIT;RETURN;
END;
/

SHOW ERRORS