/* ------------------------------------
COPYRIGHT (C) 2010-2015 LINKAGE SOFTWARE 
 ALL RIGHTS RESERVED.
<AUTHOR>JIANGBB</AUTHOR>
<CREATEDATE>2014-08-08</CREATEDATE>
<DESCRIPTION>业务金额修改存储过程</DESCRIPTION>
------------------------------------ */
CREATE OR REPLACE PROCEDURE SP_PN_TradeAmend
(
	P_TRADEID			CHAR,	--TRADEID
	P_NEXTMONEY			CHAR,	--MEXTMONEY
	
	P_CURROPER          CHAR,
    P_CURRDEPT          CHAR,
    P_RETCODE   		OUT CHAR, 		-- RETURN CODE
    P_RETMSG    		OUT VARCHAR2	-- RETURN MESSAGE
)
AS		
    V_SEQ				CHAR(16);		--序号
	V_TODAY         	DATE := SYSDATE;--日期
	V_EX				EXCEPTION;		--错误信息
BEGIN
	
	--GET TRADE ID
	SP_GETSEQ(SEQ => V_SEQ);
	
	--更新业务数据修改台帐表
	BEGIN
		INSERT INTO TF_B_BFJ_TRADEAMEND
			(TRADEID		,SYSTEMTRADEID		,PREMONEY		,NEXTMONEY,
			UPDATETIME		,STAFFNO)
		SELECT V_SEQ		,TRADEID			,TRADEMONEY		,P_NEXTMONEY,
			V_TODAY			,P_CURROPER
		FROM TF_F_BFJ_TRADERECORD
		WHERE TRADEID = P_TRADEID;
		
		IF  SQL%ROWCOUNT != 1 THEN RAISE V_EX; END IF;
		EXCEPTION
			WHEN OTHERS THEN
			P_RETCODE := 'S05041B002'; P_RETMSG  := '更新业务数据修改台帐表,'||SQLERRM;
			ROLLBACK; RETURN;
	END;
	
	--更新业务账单表
	BEGIN
		UPDATE TF_F_BFJ_TRADERECORD T 
		SET T.TRADEMONEY = P_NEXTMONEY,
			T.LEFTMONEY	 = P_NEXTMONEY
		WHERE T.TRADEID = P_TRADEID;
		
		IF  SQL%ROWCOUNT != 1 THEN RAISE V_EX; END IF;
		EXCEPTION
			WHEN OTHERS THEN
			P_RETCODE := 'S05001B005'; P_RETMSG  := '更新银行备付金交易明细表失败,'||SQLERRM;
			ROLLBACK; RETURN;
	END;
	
    P_RETCODE := '0000000000'; P_RETMSG := '';
    COMMIT;RETURN;
END;
/

SHOW ERRORS