/* ------------------------------------
COPYRIGHT (C) 2010-2015 LINKAGE SOFTWARE 
 ALL RIGHTS RESERVED.
<AUTHOR>JIANGBB</AUTHOR>
<CREATEDATE>2014-08-08</CREATEDATE>
<DESCRIPTION>网点代办业务录入存储过程</DESCRIPTION>
------------------------------------ */
CREATE OR REPLACE PROCEDURE SP_PN_DeptTradeInput
(
	P_TRADEID			CHAR,
	P_DATE				CHAR,
	P_MONEY				INT,
	P_TRADETYPE			CHAR,		--操作类型 01:新增 02:删除
	P_WELTYPE			CHAR,		--业务类型 01:公共自行车开通 02:吴江旅游年卡
	P_REMARK			CHAR,		--备注
	
	P_CURROPER          CHAR,
    P_CURRDEPT          CHAR,
    P_RETCODE   		OUT CHAR, 		-- RETURN CODE
    P_RETMSG    		OUT VARCHAR2	-- RETURN MESSAGE
)
AS		
    V_SEQ				CHAR(16);
	V_COUNT				INT:= 0;
BEGIN

	--新增功能
	IF P_TRADETYPE = '01' THEN
		--GET TRADE ID
		SP_GETSEQ(SEQ => V_SEQ);
		BEGIN
			INSERT INTO TF_F_BFJ_STAFFAGENTTRADE										
			(TRADEID,TRADETYPECODE,TRADEMONEY,
			OPERATEDEPTNO,OPERATESTAFFNO,OPERATETIME,TRADETIME,REMARK)
			VALUES
			(v_SEQ,P_WELTYPE,P_MONEY,
			P_CURRDEPT,P_CURROPER,sysdate,TO_DATE(P_DATE,'YYYYMMDD'),P_REMARK);
			EXCEPTION
				WHEN OTHERS THEN
				P_RETCODE :='S05001B010'; P_RETMSG :='更新网店代办业务登记表失败'|| SQLERRM;
				ROLLBACK;RETURN;
		END;
	--删除功能
	ELSIF P_TRADETYPE = '02' THEN
		BEGIN
			DELETE TF_F_BFJ_STAFFAGENTTRADE WHERE TRADEID = P_TRADEID;
			EXCEPTION
				WHEN OTHERS THEN
				P_RETCODE :='S05001B011'; P_RETMSG :='更新网店代办业务登记表失败'|| SQLERRM;
				ROLLBACK;RETURN;
		END;
	END IF;

    P_RETCODE := '0000000000'; P_RETMSG := '';
    COMMIT;RETURN;
END;
/

SHOW ERRORS