/* ------------------------------------
COPYRIGHT (C) 2010-2015 LINKAGE SOFTWARE 
 ALL RIGHTS RESERVED.
<AUTHOR>JIANGBB</AUTHOR>
<CREATEDATE>2014-08-08</CREATEDATE>
<DESCRIPTION>业务删除存储过程</DESCRIPTION>
------------------------------------ */
CREATE OR REPLACE PROCEDURE SP_PN_FinanceTradeDel
(
	P_TRADEID			VARCHAR2,	--流水号
	
	P_CURROPER          CHAR,
    P_CURRDEPT          CHAR,
    P_RETCODE   		OUT CHAR, -- RETURN CODE
    P_RETMSG    		OUT VARCHAR2  -- RETURN MESSAGE
)
AS
	V_SCOPECODE			CHAR(2);
	V_TODAY         	DATE := SYSDATE;
	V_RSRV1				VARCHAR(10);
	V_EX				EXCEPTION;
BEGIN

	BEGIN
		UPDATE TF_F_BFJ_TRADERECORD T 
		   SET T.ISNEEDMATCH = '1'
		 WHERE T.TRADEID = P_TRADEID;
		EXCEPTION
			WHEN OTHERS THEN
				P_RETCODE := 'S05001C002'; P_RETMSG  := '更新系统业务账单表失败,' || SQLERRM;
				ROLLBACK; RETURN;
	END;
	

    P_RETCODE := '0000000000'; P_RETMSG := '';
    COMMIT;RETURN;
END;
/

SHOW ERRORS