CREATE OR REPLACE SYNONYM TF_DEPTBALTRADE_BAL_SEQ FOR Uowner_B_SZ.TF_DEPTBALTRADE_BAL_SEQ;
CREATE OR REPLACE SYNONYM TF_DEPTBALTRADE_AllFIN_SEQ FOR Uowner_B_SZ.TF_DEPTBALTRADE_AllFIN_SEQ;
CREATE OR REPLACE SYNONYM TF_DEPTBALTRADE_OUTFIN_SEQ FOR Uowner_B_SZ.TF_DEPTBALTRADE_OUTFIN_SEQ;
CREATE OR REPLACE SYNONYM TF_DEPTBALACC_BALANCE_SEQ FOR Uowner_B_SZ.TF_DEPTBALACC_BALANCE_SEQ;
CREATE OR REPLACE SYNONYM TP_DEPTBALANCE_SEQ FOR Uowner_B_SZ.TP_DEPTBALANCE_SEQ;
CREATE OR REPLACE SYNONYM TP_DEPTFINANCE_SEQ FOR Uowner_B_SZ.TP_DEPTFINANCE_SEQ;
CREATE OR REPLACE SYNONYM TP_DEPTACCOUNT_SEQ FOR Uowner_B_SZ.TP_DEPTACCOUNT_SEQ;


