CREATE OR REPLACE SYNONYM TH_B_WARN_SEQ FOR Uowner_B_SZ.TH_B_WARN_SEQ;
CREATE OR REPLACE SYNONYM TF_B_WARN_DETAIL_SEQ FOR Uowner_B_SZ.TF_B_WARN_DETAIL_SEQ;
CREATE OR REPLACE SYNONYM TH_B_WARN_DETAIL_SEQ FOR Uowner_B_SZ.TH_B_WARN_DETAIL_SEQ;
CREATE OR REPLACE SYNONYM TH_B_WARN_BLACK_SEQ FOR Uowner_B_SZ.TH_B_WARN_BLACK_SEQ;
CREATE OR REPLACE SYNONYM TF_B_WARN_MONITOR_SEQ FOR Uowner_B_SZ.TF_B_WARN_MONITOR_SEQ;
CREATE OR REPLACE SYNONYM TH_B_WARN_MONITOR_SEQ FOR Uowner_B_SZ.TH_B_WARN_MONITOR_SEQ;
CREATE OR REPLACE SYNONYM TH_B_LOSS_BLACK_SEQ FOR Uowner_B_SZ.TH_B_LOSS_BLACK_SEQ;


