create table TD_M_CORP
(
  corpno                  CHAR(4) not null,
  corp                    VARCHAR(100) not null,
  callingno               CHAR(2),
  subcityno               CHAR(2),
  corpadd                 VARCHAR(50),
  corpmark                VARCHAR(50),
  linkman                 VARCHAR(10),
  corpphone               VARCHAR(40),
  usetag                  CHAR(1) not null,
  updatestaffno           CHAR(6),
  updatetime              DATE,
  remark                  VARCHAR(100),
  regioncode              CHAR(1),
  companypapertype        CHAR(2),
  companypaperno          VARCHAR(30),
  companyendtime          CHAR(8),
  papertype               CHAR(2),
  paperno                 VARCHAR(20),
  paperenddate            CHAR(8),
  registeredcapital       INTEGER,
  securityvalue           INTEGER,
  companymanagerpapertype CHAR(2),
  companymanagerno        VARCHAR(30),
  appcallingno            CHAR(1),
  managearea              VARCHAR(50),
  syncstatus              CHAR(1) default '0',
  corporation             VARCHAR(100)
)