-- =============================================
-- AUTHOR:		LIUHE
-- CREATE DATE: 2011-07-11
-- DESCRIPTION:	取得流水号12位NUMBER,地区号2+日期6+SEQ4
-- =============================================
CREATE OR REPLACE PROCEDURE SP_GETACCID(
    SEQNAME           IN VARCHAR2,  --SELNAME
    AREACODE      	  IN VARCHAR2,  --地区编码,2位数字
    ACCID  			OUT  NUMBER
)
AS
    V_DATE             VARCHAR2(10);
    V_SEQNAME          VARCHAR2(30);
    V_SQLSTR           VARCHAR2(200);
    V_SEQ              VARCHAR2(20);
BEGIN
    V_SEQNAME := LOWER(TRIM(SEQNAME));
    V_SQLSTR := 'SELECT '||V_SEQNAME||'.NEXTVAL FROM DUAL';
    EXECUTE IMMEDIATE V_SQLSTR INTO V_SEQ;

    SELECT SUBSTRB(AREACODE,1,2)||TO_CHAR(SYSDATE,'YYMMDD') INTO V_DATE FROM DUAL;
    ACCID:= V_DATE || SUBSTR('0000' || V_SEQ, -4);
  
EXCEPTION
    WHEN OTHERS THEN
    ACCID :=NULL;RAISE;
END;



/

SHOW ERRORS