CREATE OR REPLACE PROCEDURE SP_SSO_CHECKTOKEN
(
  P_STAFF CHAR,
  P_TOKEN CHAR,
  P_NEWTOKEN CHAR, --新TOKEN
  P_CURROPER CHAR, --当前操作者
  P_CURRDEPT CHAR, --当前操作者部门
  P_DEPT		 OUT CHAR, --部门
  P_STAFFNAME OUT CHAR,
  P_OPERCARDNO OUT CHAR,
  P_RETCODE  OUT CHAR, --错误编码
  P_RETMSG   OUT VARCHAR2 --错误信息
) AS
  V_EX EXCEPTION;
BEGIN

		BEGIN
			--校验令牌
			SELECT DEPARTNO,STAFFNAME,OPERCARDNO INTO P_DEPT,P_STAFFNAME,P_OPERCARDNO FROM TD_M_INSIDESTAFF WHERE STAFFNO = P_STAFF AND TOKEN = P_TOKEN;
      EXCEPTION
			WHEN NO_DATA_FOUND THEN

				 			P_RETCODE := 'S00L001002';
				      P_RETMSG := '用户认证失败，请重新登录' ;
				      RETURN;
   	END;

    BEGIN
      --清空令牌
			UPDATE TD_M_INSIDESTAFF SET TOKEN = P_NEWTOKEN ,LAST_ACTIVE_TIME = SYSDATE WHERE STAFFNO = P_STAFF;
			IF SQL%ROWCOUNT != 1 THEN
	      RAISE V_EX;
	    END IF;
	    EXCEPTION
             WHEN OTHERS THEN
				      P_RETCODE := 'S00L001003';
				      P_RETMSG := '清空令牌失败' ;
				      ROLLBACK;
				      RETURN;
		END;

  P_RETCODE := '0000000000';
  P_RETMSG := '';
  COMMIT;
  RETURN;
END;


/
SHOW ERROR;
